// <auto-generated />
using System;
using Dotnet5.GraphQL3.Store.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Dotnet5.GraphQL3.Store.Repositories.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.8.20407.4");

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("IntroduceAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7befed9-7ee1-49e1-8be2-b50f1a4f10a8"),
                            Comment = "Veniam est officiis possimus ut. Et rerum dolor numquam officia. Soluta quae et ut unde et rem mollitia magni facere. Quasi qui dolorem. Ut voluptatibus cupiditate ea sapiente est vero et aut repellendus. Saepe iste et.\n\nQui ipsa est magnam et pariatur expedita praesentium voluptatem quia. Non non perspiciatis et quia. Laudantium non ut. Vero et numquam dolorem aut autem possimus dolores. Sint voluptatibus est.\n\nAccusantium eos repudiandae voluptatem est quia veritatis. Rerum eum est quo. Voluptatibus debitis autem sunt dicta dolorum. Mollitia esse molestias molestiae veritatis. Ut sapiente quia. Commodi animi placeat non est ipsam.",
                            ProductId = new Guid("e7f38a31-5709-40c1-a434-7b4a50434e68"),
                            Title = "Odio quo in deserunt."
                        },
                        new
                        {
                            Id = new Guid("f705cae5-b317-4edc-9ec4-11449081ad80"),
                            Comment = "Fugiat quia sunt voluptas est dolorum ut dolorem saepe maiores. Sit laborum ex atque sapiente harum. Aspernatur dicta ut voluptatem quae delectus. Quia error id est magnam quae est. Molestiae tempore magnam ut minus consequuntur nisi rerum culpa totam.\n\nVoluptates neque a cumque deleniti. Sequi dolores error placeat. Magni consequuntur autem similique illo et dolor rerum earum. Quasi sit soluta ut doloribus eveniet exercitationem possimus. Expedita omnis et cum.\n\nId et dolorem. Saepe incidunt eum. Eos quia nulla earum natus quis aliquam in. Tempore omnis quo reiciendis minima totam corrupti nemo eos. Commodi explicabo quaerat optio qui dolorem cupiditate qui.",
                            ProductId = new Guid("ecbdf03a-dc12-4a35-ab61-c55d959ecaff"),
                            Title = "Aut mollitia ab molestias est quas illum aut."
                        },
                        new
                        {
                            Id = new Guid("8dd94aa6-bdd5-4da1-ad89-83604be5e7d4"),
                            Comment = "Minus totam earum quaerat est omnis consequuntur repellendus et quia. Soluta id doloremque corrupti sit qui. Molestiae qui est eaque fugiat provident iure.\n\nIpsa voluptatem rem praesentium ex nisi ut consequuntur. Quam fugiat sed recusandae voluptas. Blanditiis magni quis sit vero sit.\n\nEt eius soluta placeat sit optio harum velit. Quos dolores vitae quidem deserunt eos vitae suscipit reprehenderit. Eius animi placeat et quos quasi qui culpa nihil dolore.",
                            ProductId = new Guid("6be22f13-2662-4e8e-8c29-ac64f0cc6030"),
                            Title = "Autem est accusantium."
                        },
                        new
                        {
                            Id = new Guid("1d3c6d80-9585-49d2-9431-1e8b764e9ccd"),
                            Comment = "Et cum deserunt neque molestiae rerum aut. Ipsa et et maxime et ut sed repellat totam aut. Quasi ipsum sequi amet soluta temporibus sed molestiae dolorem. Sed cupiditate inventore sequi eaque dolorum voluptate maxime tempora.\n\nDeserunt repellendus voluptatem eligendi dolorem est quo. Ipsa inventore et et modi velit. Sunt corrupti voluptates autem nemo quo. Ratione et ad amet deserunt dolorem est quibusdam aliquam.\n\nTempora deleniti eum magni dolores vero qui ea. Quia omnis non accusantium fugiat quod. Provident sint fugiat at ipsum eos maxime rerum.",
                            ProductId = new Guid("509dde22-cf6b-42c3-b21a-513ad3670cf6"),
                            Title = "Esse quidem inventore."
                        },
                        new
                        {
                            Id = new Guid("54b973d9-c6ae-4c29-a144-8ba3a540acbc"),
                            Comment = "Dolore aut nam accusamus repellat recusandae repellat a doloribus. Incidunt ut incidunt. Iure impedit dolore ex pariatur dolorem fugit debitis. Reprehenderit praesentium commodi minus maxime doloremque. Eius vitae sint. Debitis tenetur unde nesciunt fugiat consequatur distinctio sunt.\n\nDolorum enim harum accusantium magnam reprehenderit ipsum veniam non. Cum consequatur eum ad voluptate quidem sed aliquam. Repudiandae quo voluptatem iure sed nulla et neque dicta occaecati. Molestias perspiciatis hic. Assumenda consectetur qui impedit quos rerum voluptates recusandae. Autem perferendis molestias sunt enim facere velit est ea.\n\nEarum totam aut. Dolor qui tempora. Omnis ipsum numquam. Esse id quas eius. Quos omnis veniam alias ut ad deserunt cupiditate suscipit vero.",
                            ProductId = new Guid("ebf718e8-8c89-4e9e-aa71-88aac943d5d7"),
                            Title = "Suscipit voluptatem iusto aut saepe recusandae nihil corporis nemo quidem."
                        },
                        new
                        {
                            Id = new Guid("33c005a9-7ffc-401f-a07b-093021e166ed"),
                            Comment = "Esse dolorem quia nihil culpa aut explicabo quo. Provident exercitationem fugit facilis consequatur aut eaque consectetur quis. Voluptas sapiente suscipit maxime dignissimos id aut. Deleniti aperiam sed voluptates. Sapiente dicta et dolor qui.\n\nFacilis et voluptatem. Et accusantium voluptatem praesentium. Et nam aut sit veritatis est quo. Beatae qui ut. Rerum laborum aut error fuga voluptatem.\n\nEt fugiat enim dolorum ad molestiae mollitia. Quia earum esse esse et quo iste consequatur explicabo necessitatibus. Ad autem repellendus aspernatur.",
                            ProductId = new Guid("c0ff065a-7bcb-4a7a-bbd9-398a9a4d1cc1"),
                            Title = "Id perspiciatis consequatur et numquam natus dolor alias dolorem ut."
                        },
                        new
                        {
                            Id = new Guid("231ffc6d-255a-4a57-b44b-f45fef7fe325"),
                            Comment = "Ex quos maxime. Sunt est officiis eos. Omnis illum molestiae illo odio.\n\nIllum debitis sit porro id enim perferendis qui. Delectus est est voluptas esse dolore placeat nobis totam aut. Ratione quasi sit id voluptates sapiente nobis. Est beatae in.\n\nDucimus sit nostrum. Enim aliquid ipsa voluptatum perferendis numquam consequuntur quae. Quis ut nemo quasi. Officia molestiae accusamus qui. Optio in aut omnis et delectus consequatur nulla. Rerum iste voluptatem incidunt a accusantium.",
                            ProductId = new Guid("a2918028-bf5c-433b-b0f3-085dcee35a1b"),
                            Title = "Fugit ut consequuntur dolores at."
                        },
                        new
                        {
                            Id = new Guid("52acb47a-5294-449d-9135-cbbff95ad96f"),
                            Comment = "Nobis officia dolor maxime expedita quo maiores. Modi eos iusto deserunt qui. In velit excepturi aut quis minus aut.\n\nTempore aliquid ipsa. Rem praesentium quod qui saepe rerum voluptatem quia amet. Modi aliquid consequatur ea mollitia suscipit praesentium autem commodi. Et ut iste et consequuntur atque quia blanditiis perferendis provident. Reprehenderit laborum delectus.\n\nDeleniti voluptate ut tenetur quia eum iure similique nostrum expedita. Voluptas quas suscipit mollitia debitis. Nesciunt consequatur non et consequuntur voluptas velit ipsam similique odit. Id eum id ipsa necessitatibus nihil vero ab. Voluptate omnis deleniti voluptatem doloribus.",
                            ProductId = new Guid("d605afe8-38a9-4971-8a82-af375a0ff295"),
                            Title = "Totam sed repellat hic soluta."
                        },
                        new
                        {
                            Id = new Guid("e9c7d116-d1bb-4cbd-b854-3a046653ab24"),
                            Comment = "Ea qui sapiente qui. Aliquid vitae consequuntur quidem iste ad minus eum praesentium et. Iusto et voluptatum perspiciatis dolorum. Qui cupiditate omnis sint et vero exercitationem. Et molestiae porro et molestiae. Beatae nemo quisquam quas delectus.\n\nQuia sed quam nesciunt et unde autem natus voluptatem. Reprehenderit laborum dolorem inventore. Aut quasi omnis tempora fugiat voluptatem.\n\nPerferendis sit aperiam quidem et magni vitae aut culpa. Aut amet voluptatem ea possimus recusandae. Et omnis totam tempora voluptas. Id tempora rerum et est tenetur quod nostrum blanditiis enim. Ea dolorem fugiat voluptates unde. Et incidunt vel sed sit accusamus.",
                            ProductId = new Guid("3287229c-8126-4ff6-b08d-4b7410bd1c35"),
                            Title = "Dignissimos enim et."
                        },
                        new
                        {
                            Id = new Guid("c5e5386d-f5ed-4dc7-90a4-55c918deebdf"),
                            Comment = "Natus totam fuga est dignissimos. Voluptate id harum et voluptatem quo. Aliquid sint sapiente tenetur. Aut in hic sit in repellat excepturi assumenda qui ea. Illo laboriosam suscipit eum a eveniet et. Quo vel in quas rerum quibusdam quidem quia.\n\nNam tenetur nesciunt corrupti vel sint excepturi eum tempora et. Quia cum nulla quae dicta in explicabo nobis. Et blanditiis fugit. Et omnis cumque eveniet. Provident voluptas temporibus. At sint voluptate ea error a qui.\n\nLibero minus odit sed nihil iste blanditiis. Eius ut cupiditate sapiente tempore non quo non dolore. Vel et vel eligendi corporis quo quidem qui molestiae. Est aut dolores et optio libero repellendus vel.",
                            ProductId = new Guid("75b68dd9-6196-4a8d-8255-b05334e76fa0"),
                            Title = "Nihil nulla ratione."
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.ValueObjects.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductType");
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Backpacks.Backpack", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BackpackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Backpack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89b7b202-3fb2-4613-9a78-f9c60ac3ce32"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 24, 7, 5, 50, 681, DateTimeKind.Unspecified).AddTicks(4536), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Concrete Chair",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=68&blur",
                            Price = 555.26m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 8,
                            Stock = 4633,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("7913ff8e-96f6-45a0-9f64-1ca806283cf6"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 10, 27, 7, 33, 16, 398, DateTimeKind.Unspecified).AddTicks(4255), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Rubber Sausages",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=307&blur",
                            Price = 673.35m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 7,
                            Stock = 1974,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("0bb19e74-6a7d-45a1-a4e7-2de6e7c2872a"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 12, 4, 20, 9, 119, DateTimeKind.Unspecified).AddTicks(99), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Soft Hat",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=501&blur",
                            Price = 109.11m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 5,
                            Stock = 1229,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("9b8e0624-75a1-4f3f-8d90-bd2b24263313"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 28, 8, 22, 55, 858, DateTimeKind.Unspecified).AddTicks(3973), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Fresh Chips",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=406&blur",
                            Price = 258.29m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 2,
                            Stock = 2262,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("2cd1644d-81ed-48a0-8860-a20d5ae885b7"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 12, 28, 19, 10, 3, 552, DateTimeKind.Unspecified).AddTicks(9468), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Fantastic Cotton Mouse",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=652&blur",
                            Price = 449.52m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 0,
                            Stock = 3875,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("436ea568-ece0-43f6-a7d7-9bbea9f3362e"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 9, 0, 53, 48, 348, DateTimeKind.Unspecified).AddTicks(5148), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Frozen Salad",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=85&blur",
                            Price = 716.56m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 2,
                            Stock = 4093,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("c2a98a49-de9d-42dc-beb2-bccf2cc3ec77"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 12, 22, 6, 35, 23, 959, DateTimeKind.Unspecified).AddTicks(5490), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Granite Car",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=426&blur",
                            Price = 369.36m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 1,
                            Stock = 1085,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("940abbf5-12f2-4dec-b163-4794aa48b9b7"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 12, 17, 11, 4, 17, 344, DateTimeKind.Unspecified).AddTicks(9961), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Metal Tuna",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=373&blur",
                            Price = 607.52m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 6,
                            Stock = 2095,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("5202c2f1-0385-412b-9f7b-dabd647ca3a1"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 7, 3, 48, 34, 533, DateTimeKind.Unspecified).AddTicks(7009), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handcrafted Concrete Computer",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=872&blur",
                            Price = 193.03m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 5,
                            Stock = 2146,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("7eba66df-43a4-43aa-ac78-8812d7e33514"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 11, 10, 17, 31, 37, 316, DateTimeKind.Unspecified).AddTicks(2864), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Metal Shirt",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=167&blur",
                            Price = 664.47m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 7,
                            Stock = 4659,
                            BackpackType = "DayPack"
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Boots.Boot", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BootType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Boot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf5ee50f-f503-4be0-b808-d3011cd8b0a9"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 9, 21, 25, 4, 739, DateTimeKind.Unspecified).AddTicks(6628), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Soft Bike",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=736&blur",
                            Price = 48.97m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 7,
                            Stock = 2462,
                            BootType = "Football",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("3b2f6ce4-1b1d-4376-80a6-0b8d51932757"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 3, 20, 52, 56, 798, DateTimeKind.Unspecified).AddTicks(6485), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Frozen Ball",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=602&blur",
                            Price = 203.45m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 6,
                            Stock = 433,
                            BootType = "Chelsea",
                            Size = 29
                        },
                        new
                        {
                            Id = new Guid("af369ce8-c02e-4483-822e-11232c2a23c1"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 27, 8, 36, 3, 643, DateTimeKind.Unspecified).AddTicks(5570), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Fresh Chicken",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1054&blur",
                            Price = 756.00m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 10,
                            Stock = 3894,
                            BootType = "Harness",
                            Size = 23
                        },
                        new
                        {
                            Id = new Guid("f9217e28-d6cd-4c15-9225-cf6ce1210d76"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 11, 15, 2, 23, 19, 518, DateTimeKind.Unspecified).AddTicks(2258), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Plastic Bacon",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=99&blur",
                            Price = 643.48m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 8,
                            Stock = 3477,
                            BootType = "Drysuit",
                            Size = 21
                        },
                        new
                        {
                            Id = new Guid("c206c776-51d4-4cc6-8623-598224bd4d0a"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 2, 9, 4, 38, 10, 985, DateTimeKind.Unspecified).AddTicks(6311), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Rubber Sausages",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=830&blur",
                            Price = 999.39m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 10,
                            Stock = 2234,
                            BootType = "Football",
                            Size = 30
                        },
                        new
                        {
                            Id = new Guid("8188cefe-898b-48aa-989b-a2e92f7c9f66"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 17, 23, 46, 26, 869, DateTimeKind.Unspecified).AddTicks(9510), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Fresh Bacon",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=48&blur",
                            Price = 390.87m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 3,
                            Stock = 639,
                            BootType = "Engineer",
                            Size = 21
                        },
                        new
                        {
                            Id = new Guid("38d1d7bc-591c-410a-8b1a-45cf18ab88c2"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 18, 8, 48, 24, 460, DateTimeKind.Unspecified).AddTicks(7231), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Rubber Shoes",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=292&blur",
                            Price = 23.65m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 1,
                            Stock = 3326,
                            BootType = "Engineer",
                            Size = 23
                        },
                        new
                        {
                            Id = new Guid("9e37da41-a97f-4a70-b29d-2413c21c447a"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 12, 10, 12, 27, 31, 523, DateTimeKind.Unspecified).AddTicks(6023), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Fresh Chips",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=645&blur",
                            Price = 687.86m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 0,
                            Stock = 1875,
                            BootType = "Harness",
                            Size = 22
                        },
                        new
                        {
                            Id = new Guid("a197f1c3-35f1-41e0-b7fb-be528a9bed39"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 26, 4, 53, 19, 384, DateTimeKind.Unspecified).AddTicks(1053), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Granite Shoes",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=148&blur",
                            Price = 433.61m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 9,
                            Stock = 1353,
                            BootType = "Football",
                            Size = 27
                        },
                        new
                        {
                            Id = new Guid("8dceee94-060a-47d7-8564-2ebab818ab67"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 10, 14, 11, 23, 12, 749, DateTimeKind.Unspecified).AddTicks(8916), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Rubber Chicken",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=813&blur",
                            Price = 154.85m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 0,
                            Stock = 729,
                            BootType = "Harness",
                            Size = 26
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Kayaks.Kayak", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Product");

                    b.Property<int>("AmountOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("KayakType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kayak");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7f38a31-5709-40c1-a434-7b4a50434e68"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 10, 12, 3, 32, 34, 251, DateTimeKind.Unspecified).AddTicks(9837), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Steel Chips",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=630&blur",
                            Price = 244.21m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 1,
                            Stock = 3178,
                            AmountOfPerson = 3,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("ecbdf03a-dc12-4a35-ab61-c55d959ecaff"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 3, 20, 1, 29, 28, DateTimeKind.Unspecified).AddTicks(194), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Fantastic Rubber Shoes",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=889&blur",
                            Price = 981.88m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 8,
                            Stock = 718,
                            AmountOfPerson = 1,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("6be22f13-2662-4e8e-8c29-ac64f0cc6030"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 29, 15, 35, 52, 310, DateTimeKind.Unspecified).AddTicks(3794), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Cotton Towels",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=994&blur",
                            Price = 577.63m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 7,
                            Stock = 1628,
                            AmountOfPerson = 1,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("509dde22-cf6b-42c3-b21a-513ad3670cf6"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 1, 20, 53, 28, 431, DateTimeKind.Unspecified).AddTicks(1754), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Steel Mouse",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1076&blur",
                            Price = 853.92m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 1,
                            Stock = 4948,
                            AmountOfPerson = 3,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("ebf718e8-8c89-4e9e-aa71-88aac943d5d7"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 16, 14, 48, 58, 283, DateTimeKind.Unspecified).AddTicks(8930), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Cotton Hat",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=301&blur",
                            Price = 78.19m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 9,
                            Stock = 1977,
                            AmountOfPerson = 1,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("c0ff065a-7bcb-4a7a-bbd9-398a9a4d1cc1"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 12, 18, 48, 2, 933, DateTimeKind.Unspecified).AddTicks(3971), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Concrete Gloves",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=27&blur",
                            Price = 970.62m,
                            ProductTypeId = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1"),
                            Rating = 7,
                            Stock = 2673,
                            AmountOfPerson = 2,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("a2918028-bf5c-433b-b0f3-085dcee35a1b"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 11, 27, 15, 46, 22, 706, DateTimeKind.Unspecified).AddTicks(4625), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Soft Gloves",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=773&blur",
                            Price = 645.70m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 4,
                            Stock = 4579,
                            AmountOfPerson = 3,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("d605afe8-38a9-4971-8a82-af375a0ff295"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 24, 22, 45, 38, 687, DateTimeKind.Unspecified).AddTicks(3931), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Cotton Chips",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=398&blur",
                            Price = 333.37m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 9,
                            Stock = 1742,
                            AmountOfPerson = 3,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("3287229c-8126-4ff6-b08d-4b7410bd1c35"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 12, 25, 16, 28, 46, 421, DateTimeKind.Unspecified).AddTicks(614), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Soft Bike",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=969&blur",
                            Price = 112.42m,
                            ProductTypeId = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47"),
                            Rating = 9,
                            Stock = 4686,
                            AmountOfPerson = 2,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("75b68dd9-6196-4a8d-8255-b05334e76fa0"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 9, 19, 21, 25, 43, 472, DateTimeKind.Unspecified).AddTicks(8558), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Frozen Sausages",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=652&blur",
                            Price = 702.59m,
                            ProductTypeId = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b"),
                            Rating = 9,
                            Stock = 106,
                            AmountOfPerson = 3,
                            KayakType = "Family"
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.ValueObjects.ProductTypes.TypeOne", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL3.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a7778d6-ea91-4db2-b60b-c5478e689d47")
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.ValueObjects.ProductTypes.TypeThree", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL3.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeThree");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5db6a180-8d06-4bb2-8c63-be91c09621e1")
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.ValueObjects.ProductTypes.TypeTwo", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL3.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeTwo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6a4ac8a-4210-4ae1-bfde-4cf85951118b")
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("Dotnet5.GraphQL3.Store.Domain.ValueObjects.ProductTypes.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");
                });

            modelBuilder.Entity("Dotnet5.GraphQL3.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Dotnet5.GraphQL3.Store.Domain.Entities.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
