// <auto-generated />
using System;
using Dotnet5.GraphQL.WebApplication.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotnet5.GraphQL.WebApplication.Repositories.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20200728194047_First migration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20372.13");

            modelBuilder.Entity("Dotnet5.GraphQL.WebApplication.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("IntroduceAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("adb244f4-93b0-46cc-9ca3-f689ddec33d5"),
                            Description = "Ut aut eveniet nam et dolor.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 4, 19, 23, 53, 398, DateTimeKind.Unspecified).AddTicks(4731), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "rerum",
                            Option = "One",
                            PhotoFileName = "generic.pdf",
                            Price = 0.4267536017734210019142732227m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = 55682484,
                            Stock = -718836233
                        },
                        new
                        {
                            Id = new Guid("3c7f4fa0-f12c-4f36-923b-a77d646b0c96"),
                            Description = "Est expedita qui et molestiae corrupti.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 2, 24, 16, 34, 32, 70, DateTimeKind.Unspecified).AddTicks(8610), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "id",
                            Option = "Two",
                            PhotoFileName = "upgradable_facilitator_home__garden_&_jewelery.pdf",
                            Price = 0.1190131917541015199038455598m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -1752806857,
                            Stock = -1522499283
                        },
                        new
                        {
                            Id = new Guid("1130bbbd-15d8-4ee2-8370-97d4d21f3b9b"),
                            Description = "Sit non adipisci amet illo.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 31, 16, 45, 56, 243, DateTimeKind.Unspecified).AddTicks(8382), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "consequuntur",
                            Option = "One",
                            PhotoFileName = "ghana_sleek.mpg4",
                            Price = 0.5442267046919565054556412204m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 3060078,
                            Stock = -1074365527
                        },
                        new
                        {
                            Id = new Guid("2dc40f32-394d-4d00-a11b-8f3f3e682199"),
                            Description = "Aut debitis sit voluptatem quis dolores.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 15, 19, 34, 48, 349, DateTimeKind.Unspecified).AddTicks(60), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "nobis",
                            Option = "One",
                            PhotoFileName = "primary_budgetary_management.shtml",
                            Price = 0.4655323607678552017440346688m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -1835792590,
                            Stock = 548468186
                        },
                        new
                        {
                            Id = new Guid("45726199-36c4-454f-9c4a-0f0439c928b1"),
                            Description = "Laboriosam exercitationem quia odit rerum quia dolore.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 9, 7, 47, 17, 927, DateTimeKind.Unspecified).AddTicks(2870), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "laboriosam",
                            Option = "One",
                            PhotoFileName = "auxiliary.mpga",
                            Price = 0.5255873025223053229954595736m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 1819392340,
                            Stock = 95534002
                        },
                        new
                        {
                            Id = new Guid("574dd632-4bbd-468b-b985-5b6b8fbfa32d"),
                            Description = "Incidunt perspiciatis ducimus facilis soluta.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 1, 11, 10, 20, 19, 649, DateTimeKind.Unspecified).AddTicks(5375), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "consequuntur",
                            Option = "Two",
                            PhotoFileName = "plum_administrator.shtml",
                            Price = 0.5803605953381957007074037228m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 368462929,
                            Stock = -2139112908
                        },
                        new
                        {
                            Id = new Guid("169e465d-df20-479e-a3d5-4dfb96ed688a"),
                            Description = "Deserunt error nesciunt est eveniet nulla voluptates.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 8, 4, 2, 3, 2, 600, DateTimeKind.Unspecified).AddTicks(8123), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "et",
                            Option = "Three",
                            PhotoFileName = "burkina_faso_alabama_copy.htm",
                            Price = 0.300687550351743267145390609m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 656449355,
                            Stock = -1130075871
                        },
                        new
                        {
                            Id = new Guid("b660a2bf-b13d-43ee-bb2c-43f455a4fe95"),
                            Description = "Doloremque enim accusamus provident dolor.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 8, 6, 17, 50, 7, 92, DateTimeKind.Unspecified).AddTicks(2153), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "vel",
                            Option = "Three",
                            PhotoFileName = "brooks.mp4",
                            Price = 0.5797581981148521017109817486m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -1967378993,
                            Stock = 138844267
                        },
                        new
                        {
                            Id = new Guid("da1df08c-b5e9-4588-96d2-9e08ed995e19"),
                            Description = "Excepturi earum dicta.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 2, 17, 23, 58, 58, 57, DateTimeKind.Unspecified).AddTicks(9611), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "autem",
                            Option = "One",
                            PhotoFileName = "response_mill_smtp.jpe",
                            Price = 0.6771927152106310208833630834m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 1848555460,
                            Stock = 1911637293
                        },
                        new
                        {
                            Id = new Guid("7f04598e-0596-4141-ba04-30ef378be2fb"),
                            Description = "Dolor consequatur repellendus necessitatibus consequuntur eaque occaecati ut vitae qui.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 2, 6, 21, 49, 51, 175, DateTimeKind.Unspecified).AddTicks(2149), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "dolor",
                            Option = "One",
                            PhotoFileName = "matrix_tertiary.mp4v",
                            Price = 0.2598383265850689116039089721m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -1268733365,
                            Stock = 1241428926
                        },
                        new
                        {
                            Id = new Guid("a76ef158-d563-4b19-9eda-44e2cf61c257"),
                            Description = "Porro est dolor ad quibusdam laborum quod.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 18, 3, 57, 8, 614, DateTimeKind.Unspecified).AddTicks(7276), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "sapiente",
                            Option = "Three",
                            PhotoFileName = "violet_liaison_regional.wav",
                            Price = 0.7099313188565726639114294545m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = 1120328551,
                            Stock = 422856575
                        },
                        new
                        {
                            Id = new Guid("41562997-1443-42a4-bd8c-5a480f0dae4e"),
                            Description = "Ut quisquam reiciendis veritatis error itaque quo blanditiis minima repellat.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 8, 2, 23, 23, 25, 670, DateTimeKind.Unspecified).AddTicks(6365), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "provident",
                            Option = "Two",
                            PhotoFileName = "initiatives_books.png",
                            Price = 0.5239162225942858735071443871m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 804636033,
                            Stock = -1758208480
                        },
                        new
                        {
                            Id = new Guid("f77cfc0b-9305-4ca7-b001-a1f4a13c6dbd"),
                            Description = "Quod numquam quisquam perferendis.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 8, 18, 14, 52, 9, 456, DateTimeKind.Unspecified).AddTicks(3906), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "suscipit",
                            Option = "Three",
                            PhotoFileName = "home_loan_account_withdrawal.png",
                            Price = 0.5886914423167658677396645519m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 627888246,
                            Stock = -23767516
                        },
                        new
                        {
                            Id = new Guid("b6df6e39-e89e-47a6-86ba-e1c1731153ca"),
                            Description = "Consequatur qui fugiat odio enim voluptatum libero reprehenderit rerum quia.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 1, 8, 17, 51, 30, 601, DateTimeKind.Unspecified).AddTicks(4979), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "asperiores",
                            Option = "Three",
                            PhotoFileName = "invoice.mpg4",
                            Price = 0.8969866252591404898682960543m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -1680015234,
                            Stock = 1654909226
                        },
                        new
                        {
                            Id = new Guid("9a569985-5140-442b-97f3-7c2528e53d29"),
                            Description = "Molestiae nam tempora.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 9, 11, 11, 23, 30, 895, DateTimeKind.Unspecified).AddTicks(4580), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "ut",
                            Option = "One",
                            PhotoFileName = "bypass_user_centric_payment.pdf",
                            Price = 0.244840821171713247378281287m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -175384519,
                            Stock = 1987519711
                        },
                        new
                        {
                            Id = new Guid("8264de00-7e7a-4077-895e-2822d7c604a4"),
                            Description = "Amet sed officiis dolorem incidunt cumque omnis dolor.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 11, 19, 48, 54, 917, DateTimeKind.Unspecified).AddTicks(1907), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "assumenda",
                            Option = "One",
                            PhotoFileName = "ethiopian_birr_consultant_violet.mp2a",
                            Price = 0.3436509478710859041515680574m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -862880450,
                            Stock = -1144127978
                        },
                        new
                        {
                            Id = new Guid("38fc9e49-cfb5-486e-99f5-609d06602cad"),
                            Description = "At aperiam deserunt eos totam.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 12, 13, 31, 28, 760, DateTimeKind.Unspecified).AddTicks(2705), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "dignissimos",
                            Option = "Three",
                            PhotoFileName = "clear_thinking_supervisor_suriname.mpg4",
                            Price = 0.464845846656858661007957371m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -1920588801,
                            Stock = -1338718242
                        },
                        new
                        {
                            Id = new Guid("66e9ee47-38f6-4825-a5a6-088aa05d2c78"),
                            Description = "Totam et et atque cum nulla eius iure.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 23, 9, 37, 16, 56, DateTimeKind.Unspecified).AddTicks(6160), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "quo",
                            Option = "Two",
                            PhotoFileName = "system_principal_adp.jpe",
                            Price = 0.9198906801305100433233638206m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -283516392,
                            Stock = 1323255039
                        },
                        new
                        {
                            Id = new Guid("b5e1223e-98bd-48d6-9380-11d0ccecec0c"),
                            Description = "Eligendi enim illum perspiciatis consequuntur.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 2, 5, 20, 29, 34, 271, DateTimeKind.Unspecified).AddTicks(8790), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "pariatur",
                            Option = "Three",
                            PhotoFileName = "bedfordshire_cotton_arizona.pdf",
                            Price = 0.6358834562785836513110541414m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -161005178,
                            Stock = -945024895
                        },
                        new
                        {
                            Id = new Guid("ba1d27ed-41e0-4132-973c-b28fde1ba278"),
                            Description = "Est aut repellendus ratione iusto aperiam dolor dicta quam placeat.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 30, 2, 12, 46, 620, DateTimeKind.Unspecified).AddTicks(599), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "mollitia",
                            Option = "Three",
                            PhotoFileName = "website_metal_sleek_soft_salad.shtml",
                            Price = 0.2131732951416561108068106515m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 2077971103,
                            Stock = 821979656
                        },
                        new
                        {
                            Id = new Guid("5910a0c0-20ab-4d72-a537-ec16682afa78"),
                            Description = "Ut tempora consequuntur consequatur.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 24, 16, 9, 35, 33, DateTimeKind.Unspecified).AddTicks(117), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "rerum",
                            Option = "One",
                            PhotoFileName = "iraqi_dinar.mpe",
                            Price = 0.5913438407511906258312537591m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 1431810734,
                            Stock = 826072615
                        },
                        new
                        {
                            Id = new Guid("9a162721-a44d-4a0b-b411-c13cc1a65bf3"),
                            Description = "Ipsam corporis laudantium esse et commodi est.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 1, 2, 50, 23, 460, DateTimeKind.Unspecified).AddTicks(6280), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "sed",
                            Option = "Three",
                            PhotoFileName = "online_applications_representative.mp4",
                            Price = 0.5447053174956262790993096593m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = -461831353,
                            Stock = -1495460688
                        },
                        new
                        {
                            Id = new Guid("20d45f52-12a9-49b3-9fa4-7c6bf582f8f0"),
                            Description = "Iure amet quas eligendi occaecati deleniti placeat dolorem aut aliquam.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 21, 14, 43, 11, 411, DateTimeKind.Unspecified).AddTicks(4229), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "qui",
                            Option = "Three",
                            PhotoFileName = "executive_ameliorated.pdf",
                            Price = 0.0765260349020219327594337257m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -1900717496,
                            Stock = -1108303290
                        },
                        new
                        {
                            Id = new Guid("b281d7fe-2b2b-4a59-8a89-16b4d02d6002"),
                            Description = "Mollitia nulla voluptate nostrum iusto omnis rem totam asperiores.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 11, 24, 12, 14, 41, 369, DateTimeKind.Unspecified).AddTicks(6741), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "odio",
                            Option = "Three",
                            PhotoFileName = "trinidad_and_tobago_compressing_online.pdf",
                            Price = 0.1861921032243692505812523007m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = 1896739424,
                            Stock = 1915661590
                        },
                        new
                        {
                            Id = new Guid("084d5a10-1875-4bca-9ff4-08b37379893e"),
                            Description = "Non perspiciatis autem pariatur quasi et dolore.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 2, 28, 17, 59, 38, 163, DateTimeKind.Unspecified).AddTicks(6651), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "dolorum",
                            Option = "Three",
                            PhotoFileName = "primary.m2v",
                            Price = 0.2919590241926060138769408534m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -1393934895,
                            Stock = -497168835
                        },
                        new
                        {
                            Id = new Guid("6026f4c3-0740-4b17-b734-f2b09e8e4fbc"),
                            Description = "Aliquid temporibus aut et expedita.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 22, 15, 42, 1, 886, DateTimeKind.Unspecified).AddTicks(7497), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "ea",
                            Option = "Three",
                            PhotoFileName = "integrate_row.mpg4",
                            Price = 0.6992173207954006432008399465m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 44266166,
                            Stock = 1148834060
                        },
                        new
                        {
                            Id = new Guid("82e965de-7bbe-4170-8e28-d2da22e5045d"),
                            Description = "Dolor beatae illum facere voluptatem neque.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 1, 21, 22, 24, 7, 125, DateTimeKind.Unspecified).AddTicks(8155), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "saepe",
                            Option = "One",
                            PhotoFileName = "hard_drive_incredible_cotton_gloves_music__clothing_&_books.jpg",
                            Price = 0.2609297952621578049124692442m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 1710069284,
                            Stock = 256678717
                        },
                        new
                        {
                            Id = new Guid("3b32d8d8-9e06-4780-b041-d08024da5b7b"),
                            Description = "Et ut veniam qui sunt sit eveniet.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 1, 21, 9, 7, 27, 980, DateTimeKind.Unspecified).AddTicks(7623), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "mollitia",
                            Option = "Three",
                            PhotoFileName = "rss.m3a",
                            Price = 0.8863683489000210023310920522m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 1504446395,
                            Stock = 1455542705
                        },
                        new
                        {
                            Id = new Guid("1fd3e239-b3bb-43ee-8c51-a773835e50a8"),
                            Description = "Id est vero consequuntur voluptatum ipsa.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 11, 16, 2, 24, 333, DateTimeKind.Unspecified).AddTicks(1706), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "quibusdam",
                            Option = "Three",
                            PhotoFileName = "lesotho_loti_refined_rubber_chair.shtml",
                            Price = 0.5429116419536869687929384788m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 156219475,
                            Stock = 969777779
                        },
                        new
                        {
                            Id = new Guid("a8096e8f-18bc-44fa-8f29-3cbd794c37ec"),
                            Description = "Natus perspiciatis placeat est nostrum quibusdam quod beatae.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 12, 16, 12, 36, 48, 351, DateTimeKind.Unspecified).AddTicks(6898), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "et",
                            Option = "Three",
                            PhotoFileName = "generic_steel_salad_purple.png",
                            Price = 0.6500673113313861777176379225m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -366350451,
                            Stock = 1211178931
                        },
                        new
                        {
                            Id = new Guid("4248fe54-51a9-481b-8973-5903747cc571"),
                            Description = "Eos autem consequuntur iusto in illo.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 11, 9, 16, 52, 58, 375, DateTimeKind.Unspecified).AddTicks(3179), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "ut",
                            Option = "One",
                            PhotoFileName = "invoice.m2v",
                            Price = 0.689707826189577230017495704m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 1364827724,
                            Stock = -1484623805
                        },
                        new
                        {
                            Id = new Guid("1713f998-d79b-48a5-a000-caee10c14393"),
                            Description = "Atque et sint.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 15, 3, 31, 31, 617, DateTimeKind.Unspecified).AddTicks(3781), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "architecto",
                            Option = "Three",
                            PhotoFileName = "palladium_projection.mpe",
                            Price = 0.2156243798339802708969603336m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 294889473,
                            Stock = -130299938
                        },
                        new
                        {
                            Id = new Guid("363720ba-f91b-49bd-a8ff-e05ce856a905"),
                            Description = "Inventore labore temporibus enim in ut sed magnam exercitationem.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 2, 22, 4, 11, 28, 34, DateTimeKind.Unspecified).AddTicks(5278), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "commodi",
                            Option = "One",
                            PhotoFileName = "leverage_blue_smtp.mpe",
                            Price = 0.0777496753127967719569267763m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = -1475959454,
                            Stock = 1509031842
                        },
                        new
                        {
                            Id = new Guid("3bfe07ab-4ec3-4914-829e-0aa19bb1b713"),
                            Description = "Sed perferendis consequatur et harum impedit sed est.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 10, 14, 14, 30, 9, 914, DateTimeKind.Unspecified).AddTicks(5552), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "corrupti",
                            Option = "One",
                            PhotoFileName = "port_unbranded_rubber_table.htm",
                            Price = 0.6886681380208842648336936335m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 1930270419,
                            Stock = 1127582787
                        },
                        new
                        {
                            Id = new Guid("007e2615-76fb-4797-a6b7-153776205474"),
                            Description = "Amet explicabo dolor similique illum quia.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 10, 19, 13, 4, 8, 174, DateTimeKind.Unspecified).AddTicks(3031), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "reiciendis",
                            Option = "One",
                            PhotoFileName = "system.mpg4",
                            Price = 0.1956164609161283548890878113m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 576536332,
                            Stock = 1128111987
                        },
                        new
                        {
                            Id = new Guid("6c48fed6-fba7-49fb-9244-c5dd17585cb1"),
                            Description = "A odio hic quia ut animi qui.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 9, 11, 12, 56, 45, 799, DateTimeKind.Unspecified).AddTicks(9643), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "iste",
                            Option = "One",
                            PhotoFileName = "director.mp4",
                            Price = 0.0068997858436220081788350754m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -264924909,
                            Stock = 1096837419
                        },
                        new
                        {
                            Id = new Guid("a3c1ee5c-d5c1-4b81-958a-a2f1555f2e7e"),
                            Description = "Possimus pariatur sint pariatur consectetur qui.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 10, 23, 5, 32, 57, 989, DateTimeKind.Unspecified).AddTicks(916), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "numquam",
                            Option = "One",
                            PhotoFileName = "sports__sports_&_electronics_haptic_payment.m2v",
                            Price = 0.2439516595311122363023317212m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 1541779640,
                            Stock = -199414292
                        },
                        new
                        {
                            Id = new Guid("997e50b0-07db-4a50-a52c-4696fb765b91"),
                            Description = "Quia eligendi enim rerum laboriosam aut accusamus non.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 8, 20, 14, 37, 41, 367, DateTimeKind.Unspecified).AddTicks(5846), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "delectus",
                            Option = "Two",
                            PhotoFileName = "invoice_tcp.pdf",
                            Price = 0.273518793226343753745186262m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -1136102131,
                            Stock = -1939776400
                        },
                        new
                        {
                            Id = new Guid("148ce96e-0d75-4b70-90e1-c13fefe1454b"),
                            Description = "Cumque velit nihil dolores.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 21, 10, 24, 57, 199, DateTimeKind.Unspecified).AddTicks(1417), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "non",
                            Option = "Two",
                            PhotoFileName = "sql_parsing.png",
                            Price = 0.4253667136990974870382060198m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 552688278,
                            Stock = -1303441614
                        },
                        new
                        {
                            Id = new Guid("3ba124b1-742c-4163-9723-7af194041109"),
                            Description = "Laudantium quia consequatur dicta eveniet nemo perferendis et.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 11, 3, 12, 32, 25, 94, DateTimeKind.Unspecified).AddTicks(5442), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "esse",
                            Option = "Three",
                            PhotoFileName = "nakfa_borders_berkshire.gif",
                            Price = 0.5908617181141403752872951538m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -2026685433,
                            Stock = -1238681101
                        },
                        new
                        {
                            Id = new Guid("c21ad3f5-7f95-4e56-a825-29012f934fa4"),
                            Description = "Quod doloribus veritatis non occaecati modi rerum expedita.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 12, 6, 18, 24, 11, 264, DateTimeKind.Unspecified).AddTicks(6978), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "et",
                            Option = "Two",
                            PhotoFileName = "http.pdf",
                            Price = 0.7289801896870299517778267633m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -354825905,
                            Stock = 1756986064
                        },
                        new
                        {
                            Id = new Guid("e0f5f2c4-3930-4353-b3d9-ee049d4bd0e3"),
                            Description = "Dolorum dolorem quas rerum sunt.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 11, 9, 0, 56, 36, 574, DateTimeKind.Unspecified).AddTicks(7832), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "earum",
                            Option = "One",
                            PhotoFileName = "e_tailers.html",
                            Price = 0.496222962922515735870755214m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 1390622677,
                            Stock = -117659637
                        },
                        new
                        {
                            Id = new Guid("5836cfbb-c041-42c4-8a26-4e071a5e9c92"),
                            Description = "Sed necessitatibus ad consequatur ut.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 2, 15, 11, 16, 19, 330, DateTimeKind.Unspecified).AddTicks(2372), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "et",
                            Option = "Two",
                            PhotoFileName = "burgs_maroon.png",
                            Price = 0.5710242712362338944943044674m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -1855730441,
                            Stock = 52303286
                        },
                        new
                        {
                            Id = new Guid("023dfe5b-bc0a-4726-949a-a1f9a0cc4d9e"),
                            Description = "Vero ut maiores laboriosam voluptatum suscipit id blanditiis qui.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 29, 5, 54, 15, 92, DateTimeKind.Unspecified).AddTicks(3043), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "dolore",
                            Option = "Two",
                            PhotoFileName = "generate.gif",
                            Price = 0.4229931449968600322070115301m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = 155629802,
                            Stock = 366800226
                        },
                        new
                        {
                            Id = new Guid("d062c082-351d-405c-ae53-dcb3b356a825"),
                            Description = "Porro eum est.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 4, 5, 13, 41, 208, DateTimeKind.Unspecified).AddTicks(9589), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "nobis",
                            Option = "Three",
                            PhotoFileName = "engage_swedish_krona.pdf",
                            Price = 0.130864308737824824277087829m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = 758030498,
                            Stock = 2087013529
                        },
                        new
                        {
                            Id = new Guid("47634ffa-53a4-43f4-bf1b-fd5a8184fc2c"),
                            Description = "Quis iure aut corrupti quae et.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 1, 15, 17, 44, 32, 240, DateTimeKind.Unspecified).AddTicks(6310), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "et",
                            Option = "Three",
                            PhotoFileName = "withdrawal_bedfordshire.pdf",
                            Price = 0.4647725638118447993996490177m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = 1304587724,
                            Stock = -1299933335
                        },
                        new
                        {
                            Id = new Guid("ce36b9da-d092-4b62-80bb-66bc0d84c5ec"),
                            Description = "Exercitationem neque sed.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 13, 2, 48, 12, 688, DateTimeKind.Unspecified).AddTicks(9038), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "et",
                            Option = "Three",
                            PhotoFileName = "collaboration_evolve.gif",
                            Price = 0.1485792720557672015226105759m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = -455209136,
                            Stock = -300774856
                        },
                        new
                        {
                            Id = new Guid("88508671-2e52-446b-b5fb-147ccf10528b"),
                            Description = "Distinctio sunt porro veniam enim dolorum officia aut eum.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 6, 1, 29, 59, 405, DateTimeKind.Unspecified).AddTicks(6157), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "quia",
                            Option = "One",
                            PhotoFileName = "e_commerce_synthesizing.mpg4",
                            Price = 0.7041807970348114000786665057m,
                            ProductTypeId = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849"),
                            Rating = 1203988474,
                            Stock = -1355882952
                        },
                        new
                        {
                            Id = new Guid("5f4795fe-505c-4304-892c-3ad05b3a5775"),
                            Description = "Omnis ea doloremque quia.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2020, 12, 13, 8, 43, 39, 984, DateTimeKind.Unspecified).AddTicks(7981), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "mollitia",
                            Option = "Three",
                            PhotoFileName = "sleek_intelligent_concrete_salad_bi_directional.mpe",
                            Price = 0.9737382135148176511833727316m,
                            ProductTypeId = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef"),
                            Rating = -1254690841,
                            Stock = -903867649
                        },
                        new
                        {
                            Id = new Guid("cddc1e4b-b11a-4354-bd1d-38c347b73924"),
                            Description = "Libero neque eos ut et sequi vel ea qui sequi.",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 5, 6, 23, 45, 818, DateTimeKind.Unspecified).AddTicks(1854), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "quo",
                            Option = "Two",
                            PhotoFileName = "fantastic_cotton_fish_product_panel.mp2a",
                            Price = 0.9427912890614097235584126396m,
                            ProductTypeId = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153"),
                            Rating = -2024878207,
                            Stock = 516270272
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL.WebApplication.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a2cde97-22a5-4c7c-b96b-309db65ecf93"),
                            Comment = "Explicabo consequatur fugiat.",
                            ProductId = new Guid("adb244f4-93b0-46cc-9ca3-f689ddec33d5"),
                            Title = "reiciendis"
                        },
                        new
                        {
                            Id = new Guid("2e6ba3de-5264-4771-8e84-7c21b32d0b35"),
                            Comment = "Qui aliquam consequuntur modi sed asperiores.",
                            ProductId = new Guid("3c7f4fa0-f12c-4f36-923b-a77d646b0c96"),
                            Title = "nemo"
                        },
                        new
                        {
                            Id = new Guid("db7383dc-a66f-45d5-9702-8348e5e509a3"),
                            Comment = "Et assumenda dolorum officia alias possimus blanditiis est delectus iste.",
                            ProductId = new Guid("1130bbbd-15d8-4ee2-8370-97d4d21f3b9b"),
                            Title = "est"
                        },
                        new
                        {
                            Id = new Guid("c2bea636-c8ad-44bc-a4d3-2bb40e2d16da"),
                            Comment = "Dolorum tempora omnis explicabo.",
                            ProductId = new Guid("2dc40f32-394d-4d00-a11b-8f3f3e682199"),
                            Title = "illum"
                        },
                        new
                        {
                            Id = new Guid("ee7e389e-fe4f-4c62-aa30-9667b08448d6"),
                            Comment = "In temporibus sit nemo nisi.",
                            ProductId = new Guid("45726199-36c4-454f-9c4a-0f0439c928b1"),
                            Title = "vitae"
                        },
                        new
                        {
                            Id = new Guid("b32026d6-bcd4-4395-b604-e1668cc16fcf"),
                            Comment = "Ipsam perferendis a ipsam rerum.",
                            ProductId = new Guid("574dd632-4bbd-468b-b985-5b6b8fbfa32d"),
                            Title = "dignissimos"
                        },
                        new
                        {
                            Id = new Guid("dcb0be34-1e5f-4731-a2fe-18cb53e84e75"),
                            Comment = "Laborum vero unde dolores odio qui ea et non.",
                            ProductId = new Guid("169e465d-df20-479e-a3d5-4dfb96ed688a"),
                            Title = "ipsam"
                        },
                        new
                        {
                            Id = new Guid("b869f231-fc4a-4190-83d9-41e90527d699"),
                            Comment = "Consequatur tempora maxime quibusdam.",
                            ProductId = new Guid("b660a2bf-b13d-43ee-bb2c-43f455a4fe95"),
                            Title = "sint"
                        },
                        new
                        {
                            Id = new Guid("66ed4e3f-8685-4405-b1a2-33366f0b0dac"),
                            Comment = "Doloremque voluptate amet mollitia occaecati similique quia nihil.",
                            ProductId = new Guid("da1df08c-b5e9-4588-96d2-9e08ed995e19"),
                            Title = "sed"
                        },
                        new
                        {
                            Id = new Guid("5f4ae97d-7b18-4fd0-a773-0d09372df007"),
                            Comment = "Nobis maxime et velit voluptatem.",
                            ProductId = new Guid("7f04598e-0596-4141-ba04-30ef378be2fb"),
                            Title = "fugit"
                        },
                        new
                        {
                            Id = new Guid("b85af1d4-8ef9-4cb3-b1fb-74335845c3c0"),
                            Comment = "Fuga voluptas cum quam expedita commodi asperiores mollitia vero.",
                            ProductId = new Guid("a76ef158-d563-4b19-9eda-44e2cf61c257"),
                            Title = "perferendis"
                        },
                        new
                        {
                            Id = new Guid("ed30172a-a2e6-4bf3-ac57-326c6ed30e62"),
                            Comment = "Provident vero natus occaecati.",
                            ProductId = new Guid("41562997-1443-42a4-bd8c-5a480f0dae4e"),
                            Title = "explicabo"
                        },
                        new
                        {
                            Id = new Guid("e7fb674f-b59d-40b4-a716-39926cdf3239"),
                            Comment = "Veniam ut quaerat ut sunt.",
                            ProductId = new Guid("f77cfc0b-9305-4ca7-b001-a1f4a13c6dbd"),
                            Title = "quis"
                        },
                        new
                        {
                            Id = new Guid("fa2ac92b-d305-4575-887d-74e89f3d89e5"),
                            Comment = "Impedit ut dolorem tempore.",
                            ProductId = new Guid("b6df6e39-e89e-47a6-86ba-e1c1731153ca"),
                            Title = "inventore"
                        },
                        new
                        {
                            Id = new Guid("8033c9a1-4e09-494c-8b84-e84182ed8c30"),
                            Comment = "Ut odit optio ducimus quia aperiam.",
                            ProductId = new Guid("9a569985-5140-442b-97f3-7c2528e53d29"),
                            Title = "et"
                        },
                        new
                        {
                            Id = new Guid("d7b14a11-0dab-40e2-b74a-60e522156340"),
                            Comment = "Quis ipsa consectetur repellat distinctio.",
                            ProductId = new Guid("8264de00-7e7a-4077-895e-2822d7c604a4"),
                            Title = "iste"
                        },
                        new
                        {
                            Id = new Guid("ff0bb057-10e4-4a6d-ae76-da350296b04e"),
                            Comment = "Saepe soluta est dolorem.",
                            ProductId = new Guid("38fc9e49-cfb5-486e-99f5-609d06602cad"),
                            Title = "est"
                        },
                        new
                        {
                            Id = new Guid("4e8cf4a1-8fde-4e46-b1bc-b5ea84a2f5d6"),
                            Comment = "Consequuntur atque at perspiciatis.",
                            ProductId = new Guid("66e9ee47-38f6-4825-a5a6-088aa05d2c78"),
                            Title = "provident"
                        },
                        new
                        {
                            Id = new Guid("e389be72-e948-49a2-88e7-258ddf3e79f2"),
                            Comment = "Qui impedit facere velit quia sed.",
                            ProductId = new Guid("b5e1223e-98bd-48d6-9380-11d0ccecec0c"),
                            Title = "molestiae"
                        },
                        new
                        {
                            Id = new Guid("d8eb5936-7cfd-4d66-ace3-ed87ded26ab5"),
                            Comment = "Architecto fugiat voluptate.",
                            ProductId = new Guid("ba1d27ed-41e0-4132-973c-b28fde1ba278"),
                            Title = "odio"
                        },
                        new
                        {
                            Id = new Guid("15528ec9-d969-4b47-89d7-a33cd645a1a7"),
                            Comment = "At ut repudiandae dolores et ut.",
                            ProductId = new Guid("5910a0c0-20ab-4d72-a537-ec16682afa78"),
                            Title = "et"
                        },
                        new
                        {
                            Id = new Guid("dd47c92a-a0df-4b74-a4b1-37099bab36a7"),
                            Comment = "Vitae vel modi odio molestias velit sit omnis.",
                            ProductId = new Guid("9a162721-a44d-4a0b-b411-c13cc1a65bf3"),
                            Title = "fuga"
                        },
                        new
                        {
                            Id = new Guid("410bd3ef-86da-48a0-ad5b-e9f7d4de2d14"),
                            Comment = "Et officia iste autem sunt et nulla accusamus praesentium.",
                            ProductId = new Guid("20d45f52-12a9-49b3-9fa4-7c6bf582f8f0"),
                            Title = "ut"
                        },
                        new
                        {
                            Id = new Guid("4eecddcb-c45e-4993-ae0b-19dea6bf9e31"),
                            Comment = "Quasi veritatis enim quis soluta autem.",
                            ProductId = new Guid("b281d7fe-2b2b-4a59-8a89-16b4d02d6002"),
                            Title = "ad"
                        },
                        new
                        {
                            Id = new Guid("291810ee-01e0-42db-8d35-cb51ef6f507a"),
                            Comment = "Maiores repellendus enim aut.",
                            ProductId = new Guid("084d5a10-1875-4bca-9ff4-08b37379893e"),
                            Title = "maxime"
                        },
                        new
                        {
                            Id = new Guid("2850b744-9f4e-4f9d-bbe3-481723e220a8"),
                            Comment = "Eveniet provident possimus vel consequuntur.",
                            ProductId = new Guid("6026f4c3-0740-4b17-b734-f2b09e8e4fbc"),
                            Title = "et"
                        },
                        new
                        {
                            Id = new Guid("486a5421-2a35-4704-b3a6-af330d0a94a4"),
                            Comment = "Ducimus doloribus et pariatur non.",
                            ProductId = new Guid("82e965de-7bbe-4170-8e28-d2da22e5045d"),
                            Title = "veritatis"
                        },
                        new
                        {
                            Id = new Guid("9d2ffd0b-6300-485b-a844-0ab5a6aeb5ae"),
                            Comment = "Exercitationem et velit est adipisci nostrum.",
                            ProductId = new Guid("3b32d8d8-9e06-4780-b041-d08024da5b7b"),
                            Title = "perferendis"
                        },
                        new
                        {
                            Id = new Guid("bb219472-baf2-4b7f-b372-8540343d8e65"),
                            Comment = "Hic sequi eum et voluptates natus quidem inventore mollitia.",
                            ProductId = new Guid("1fd3e239-b3bb-43ee-8c51-a773835e50a8"),
                            Title = "corrupti"
                        },
                        new
                        {
                            Id = new Guid("36442e9b-c307-42a8-8c6c-cffefc169a02"),
                            Comment = "Nihil cum dicta sunt illo suscipit doloribus odit dolorum.",
                            ProductId = new Guid("a8096e8f-18bc-44fa-8f29-3cbd794c37ec"),
                            Title = "architecto"
                        },
                        new
                        {
                            Id = new Guid("f1670d72-02ce-4c61-a770-1088965694d9"),
                            Comment = "Odio placeat minus debitis sint suscipit officia sed et.",
                            ProductId = new Guid("4248fe54-51a9-481b-8973-5903747cc571"),
                            Title = "qui"
                        },
                        new
                        {
                            Id = new Guid("36fe5727-aa65-486d-966d-56535bc0a6be"),
                            Comment = "Ratione culpa animi maiores excepturi.",
                            ProductId = new Guid("1713f998-d79b-48a5-a000-caee10c14393"),
                            Title = "suscipit"
                        },
                        new
                        {
                            Id = new Guid("d83964f1-6afb-440e-a4a5-68e26814d190"),
                            Comment = "Vel non et ea fugit quidem quisquam non error.",
                            ProductId = new Guid("363720ba-f91b-49bd-a8ff-e05ce856a905"),
                            Title = "qui"
                        },
                        new
                        {
                            Id = new Guid("0594a6af-bb03-4fab-9464-73476fa49168"),
                            Comment = "Sed amet qui cum dolor porro.",
                            ProductId = new Guid("3bfe07ab-4ec3-4914-829e-0aa19bb1b713"),
                            Title = "beatae"
                        },
                        new
                        {
                            Id = new Guid("4ec0f6bd-12fc-4090-a5c1-69181b38d39a"),
                            Comment = "Doloremque facilis corporis totam inventore qui ea architecto provident quas.",
                            ProductId = new Guid("007e2615-76fb-4797-a6b7-153776205474"),
                            Title = "corrupti"
                        },
                        new
                        {
                            Id = new Guid("a87cf7b8-7949-46ab-8b99-031617462e54"),
                            Comment = "Qui expedita voluptas.",
                            ProductId = new Guid("6c48fed6-fba7-49fb-9244-c5dd17585cb1"),
                            Title = "consequatur"
                        },
                        new
                        {
                            Id = new Guid("d1066d03-06a4-43bf-a7f3-1ed7f7c6bc55"),
                            Comment = "Et beatae quidem explicabo.",
                            ProductId = new Guid("a3c1ee5c-d5c1-4b81-958a-a2f1555f2e7e"),
                            Title = "nesciunt"
                        },
                        new
                        {
                            Id = new Guid("8de30d4a-83e1-4ce4-a517-a0ab17ca80e3"),
                            Comment = "Est ducimus aspernatur cumque ut a totam in.",
                            ProductId = new Guid("997e50b0-07db-4a50-a52c-4696fb765b91"),
                            Title = "rerum"
                        },
                        new
                        {
                            Id = new Guid("7815f66e-75de-49c2-a70d-17fba4aa241a"),
                            Comment = "Harum corporis magni molestias laudantium nulla omnis facere error amet.",
                            ProductId = new Guid("148ce96e-0d75-4b70-90e1-c13fefe1454b"),
                            Title = "impedit"
                        },
                        new
                        {
                            Id = new Guid("0eb32d5b-ab7e-4e32-b3d1-20b1357ba73b"),
                            Comment = "Quasi et unde.",
                            ProductId = new Guid("3ba124b1-742c-4163-9723-7af194041109"),
                            Title = "vero"
                        },
                        new
                        {
                            Id = new Guid("00b7a9ac-4731-436d-a1dd-7d8116da992f"),
                            Comment = "Sed enim quidem dignissimos repellendus accusamus earum.",
                            ProductId = new Guid("c21ad3f5-7f95-4e56-a825-29012f934fa4"),
                            Title = "non"
                        },
                        new
                        {
                            Id = new Guid("84dfa1cf-2211-40a5-ac70-7b5219dd6a64"),
                            Comment = "Sapiente aut explicabo.",
                            ProductId = new Guid("e0f5f2c4-3930-4353-b3d9-ee049d4bd0e3"),
                            Title = "sed"
                        },
                        new
                        {
                            Id = new Guid("ba20a3be-457f-42a5-a9e1-0cdd0fa82e87"),
                            Comment = "Aut animi neque.",
                            ProductId = new Guid("5836cfbb-c041-42c4-8a26-4e071a5e9c92"),
                            Title = "consectetur"
                        },
                        new
                        {
                            Id = new Guid("19c3f464-c4cb-419f-a73c-827de685c1b4"),
                            Comment = "Velit ullam soluta voluptatem corporis.",
                            ProductId = new Guid("023dfe5b-bc0a-4726-949a-a1f9a0cc4d9e"),
                            Title = "aut"
                        },
                        new
                        {
                            Id = new Guid("67bd16f3-2720-4224-9d06-cc81079a4162"),
                            Comment = "Aut asperiores optio autem atque sequi velit.",
                            ProductId = new Guid("d062c082-351d-405c-ae53-dcb3b356a825"),
                            Title = "quis"
                        },
                        new
                        {
                            Id = new Guid("d0a33148-7aac-4619-97d4-d25b42afcdcc"),
                            Comment = "Dicta dolore laudantium nulla et consectetur reiciendis odio aut saepe.",
                            ProductId = new Guid("47634ffa-53a4-43f4-bf1b-fd5a8184fc2c"),
                            Title = "distinctio"
                        },
                        new
                        {
                            Id = new Guid("f4b3cb38-bdfd-4f73-8ea5-5b4dc4cc455b"),
                            Comment = "Quia id voluptatum et nihil adipisci.",
                            ProductId = new Guid("ce36b9da-d092-4b62-80bb-66bc0d84c5ec"),
                            Title = "distinctio"
                        },
                        new
                        {
                            Id = new Guid("0944c5cb-f9b0-4747-b60d-09f5a45a6908"),
                            Comment = "At nostrum suscipit error aliquam.",
                            ProductId = new Guid("88508671-2e52-446b-b5fb-147ccf10528b"),
                            Title = "eveniet"
                        },
                        new
                        {
                            Id = new Guid("9814e6ba-8cb8-42ee-a1bf-650162c8c635"),
                            Comment = "Fugiat est deleniti qui soluta maxime magni perferendis aliquid cumque.",
                            ProductId = new Guid("5f4795fe-505c-4304-892c-3ad05b3a5775"),
                            Title = "ut"
                        },
                        new
                        {
                            Id = new Guid("a191efda-7ec0-4860-8015-d188fa6acd47"),
                            Comment = "Consequatur voluptatem labore eos voluptate eius dicta pariatur iure modi.",
                            ProductId = new Guid("cddc1e4b-b11a-4354-bd1d-38c347b73924"),
                            Title = "totam"
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL.WebApplication.Domain.ValueObjects.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Discriminator")
                        .IsUnique();

                    b.ToTable("ProductTypes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductType");
                });

            modelBuilder.Entity("Dotnet5.GraphQL.WebApplication.Domain.ValueObjects.ProductTypes.TypeOne", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL.WebApplication.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77563075-6e97-4fa6-b927-e7467fca1eef")
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL.WebApplication.Domain.ValueObjects.ProductTypes.TypeThree", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL.WebApplication.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeThree");

                    b.HasData(
                        new
                        {
                            Id = new Guid("adcbcdc3-cb25-44d0-aa77-89cf7a9c7153")
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL.WebApplication.Domain.ValueObjects.ProductTypes.TypeTwo", b =>
                {
                    b.HasBaseType("Dotnet5.GraphQL.WebApplication.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeTwo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("059b00ff-5821-4a9a-95b6-36f42c6d9849")
                        });
                });

            modelBuilder.Entity("Dotnet5.GraphQL.WebApplication.Domain.Entities.Product", b =>
                {
                    b.HasOne("Dotnet5.GraphQL.WebApplication.Domain.ValueObjects.ProductTypes.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");
                });

            modelBuilder.Entity("Dotnet5.GraphQL.WebApplication.Domain.Entities.Review", b =>
                {
                    b.HasOne("Dotnet5.GraphQL.WebApplication.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
