// <auto-generated />
using System;
using Dotnet6.GraphQL4.Store.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotnet6.GraphQL4.Store.Repositories.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20210502213436_First migration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("IntroduceAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d9dc902-fe76-4e44-beaf-e37231ca9fe3"),
                            Comment = "Quae sit ut id blanditiis. Ut dicta atque non sint eum. Non aut fugiat. Quo inventore sint qui et praesentium a est quaerat. Perferendis incidunt mollitia eum distinctio ut doloremque soluta ipsa fugit.\n\nDolor facere dolorem dicta ut distinctio voluptatem velit eaque. Qui quos est quisquam facere qui. Voluptatem sint deserunt cum ea est cupiditate reprehenderit. Architecto cupiditate enim dolore quo. Fuga facere nihil dicta nihil corrupti.\n\nMinus perferendis non rerum. Nisi consequuntur omnis laborum voluptatem quasi quis excepturi. Blanditiis nemo nesciunt nulla eum aliquam architecto eaque doloremque voluptas. Vero illo voluptates eum.",
                            ProductId = new Guid("efb39614-f2dc-489b-a458-e97e7bd49d60"),
                            Title = "Esse excepturi impedit quisquam at temporibus tenetur."
                        },
                        new
                        {
                            Id = new Guid("eb8c7018-3131-48b1-af29-d3dc1400fbbb"),
                            Comment = "Est sapiente et saepe ea ut non culpa. Cupiditate est neque ut saepe fuga suscipit nulla facilis aliquam. Et numquam enim vero magni harum itaque quae.\n\nDicta laborum ab et. Tempore dignissimos et minima distinctio soluta maiores. Qui officiis necessitatibus. Eum ut optio in voluptatem deserunt eaque sint.\n\nVoluptas officia perspiciatis sit quia quia aut et. Rerum sit aut. Iure facilis officia et mollitia quasi fugiat quae nemo. Ut enim voluptas est beatae modi ut. Ut autem eveniet voluptatem et beatae neque culpa magni sapiente. Iure enim reprehenderit iure et incidunt odio sapiente maxime et.",
                            ProductId = new Guid("8c15793b-bdf5-4818-950b-3cad57493d93"),
                            Title = "Voluptatum minima assumenda quis veritatis reiciendis facere similique iusto."
                        },
                        new
                        {
                            Id = new Guid("102fc691-c447-47a8-b274-f1d1c87925de"),
                            Comment = "Excepturi voluptas in doloremque non. Velit quidem quos consequatur et. Mollitia accusamus excepturi. Et fuga quibusdam. Cum ut ex est quae officiis modi. Cupiditate veritatis architecto sed.\n\nQuia fugit totam excepturi minus quasi. Facilis dolores molestias unde facere. Itaque perspiciatis hic provident.\n\nConsectetur dolorem earum esse saepe et et in cumque. Non culpa error. Nulla odit sequi. Et voluptatem itaque. Dolorem voluptas ad.",
                            ProductId = new Guid("2416836c-ee63-4252-9b3d-34a28d8f86c8"),
                            Title = "Ad facere tempore."
                        },
                        new
                        {
                            Id = new Guid("a702b5c9-81e6-477e-a953-721fc5a92a9f"),
                            Comment = "Ab beatae sed accusantium praesentium harum. Et est omnis eos nihil sint asperiores quas. Assumenda est ea quos eos dolor velit praesentium occaecati.\n\nVoluptatem officiis atque nisi sit necessitatibus rem. Facilis eos ullam possimus accusamus ratione. Tenetur neque laudantium suscipit rem doloremque fuga ex. Quidem recusandae dolorem maiores voluptatem et sunt ipsam temporibus.\n\nLaborum dolorum animi mollitia qui temporibus sapiente est et tenetur. Ut temporibus quis dolorem quo nisi repudiandae. Est occaecati recusandae iste earum. Qui sed totam accusantium repudiandae. Sed dicta earum maxime. Fugit omnis porro molestias nihil.",
                            ProductId = new Guid("1aff9598-62dc-4fab-83fb-d4bb71bd81ee"),
                            Title = "Dolore sapiente et aut ipsam eum."
                        },
                        new
                        {
                            Id = new Guid("124f65c6-632b-4735-abaa-a6bfa06cee06"),
                            Comment = "Rerum autem illo quia dignissimos fuga ducimus facilis nulla rem. Libero soluta nobis quis quia deserunt in nulla omnis. Autem officiis nostrum repudiandae eius voluptatem dolore ipsam neque inventore. Qui dolores delectus nostrum totam aut. Earum voluptate reprehenderit velit qui aut illo. Voluptas libero enim neque laborum illum esse.\n\nEaque eum laboriosam rerum ipsa. Quidem unde nihil nostrum. Dolorum vitae et consequatur ut quos et. Nisi consequatur magnam iste omnis sint sed adipisci. Sit illum ratione illum aut vel odit itaque occaecati. Est doloribus fuga quasi.\n\nUt eaque possimus quis aut. Eius suscipit enim ducimus minus blanditiis. Accusantium eum nemo.",
                            ProductId = new Guid("d5867a40-9000-4c19-baa2-92c88c1029ed"),
                            Title = "Suscipit quas optio necessitatibus quis quasi qui qui eaque."
                        },
                        new
                        {
                            Id = new Guid("8a8d7aec-b665-4e9a-a628-7ce00ae62551"),
                            Comment = "Commodi illo modi dolorum facere quidem maxime. Nostrum aspernatur sunt rerum explicabo eveniet. Omnis velit expedita aliquid aut voluptatem ut ut. Voluptatem voluptates sequi nulla.\n\nRepellat ut et aut. Sed et et. Consequatur optio ipsa corporis debitis tempore dolorem qui accusantium. Et magnam velit non.\n\nSint quisquam minima rerum ut aut voluptatibus sunt illo. Exercitationem accusantium repudiandae possimus voluptatem ut dicta numquam reprehenderit architecto. Qui asperiores et ut. Illum natus voluptas facilis est unde. Harum repellat eum numquam tempore earum dicta dolor fugit.",
                            ProductId = new Guid("12094de7-443d-4ebb-a887-49a01d6c5c65"),
                            Title = "Numquam suscipit illo ut voluptatem aspernatur."
                        },
                        new
                        {
                            Id = new Guid("518085b8-33c8-4c8a-ba3d-ccca7246b952"),
                            Comment = "Numquam molestiae natus est sunt consequatur tempora. Aut quia nostrum modi consequuntur quisquam cumque numquam. Beatae alias cum magnam ab id quo ea. Nihil est facere. Placeat adipisci recusandae quod a dolorem. Debitis deleniti sint.\n\nEius optio dolores est qui nam non et impedit. Cumque expedita et. Aspernatur impedit ipsum officiis. Nesciunt eos ut voluptas. Maiores repellat aliquam.\n\nEt sed repudiandae maxime est. Repellat sequi in ad fugiat velit incidunt nihil optio fugiat. Ea et rerum dignissimos minima tempora sed velit soluta quos. Laudantium voluptas nemo et impedit. Maiores possimus incidunt dolorem temporibus sapiente aut.",
                            ProductId = new Guid("f7db1c45-3751-4b21-af88-7fb951a7ce53"),
                            Title = "Illum qui totam suscipit."
                        },
                        new
                        {
                            Id = new Guid("2e5254bf-5d86-4b6a-8444-ce0e0d2109a3"),
                            Comment = "Corrupti doloremque eos eum neque. Est itaque repudiandae temporibus et ut fugit et. Autem et minus asperiores libero fugit est quod architecto.\n\nAsperiores aut omnis cum impedit. Commodi molestias tempore deleniti non nihil dolor. Enim ut eum dolorem. Velit perspiciatis voluptas. Reiciendis cupiditate commodi aut velit fugit odio.\n\nRatione totam maxime qui soluta ipsa optio. Accusamus omnis sed ut explicabo temporibus. Et repellat et itaque aut quia. Amet qui qui dolores eligendi numquam sapiente.",
                            ProductId = new Guid("c3d65c01-be1d-4577-8acd-cae54e37b4d3"),
                            Title = "Velit dolore minima."
                        },
                        new
                        {
                            Id = new Guid("ca6f8d18-17ec-49dd-9f14-310c9f1da02d"),
                            Comment = "Ea iusto officia id. Cumque sit aut fuga facere fugiat sit. Non voluptatem nisi veniam cum eum eos et.\n\nQui ullam veritatis molestiae amet. Aliquid provident sed ex officia rerum consequuntur. Dicta consectetur laboriosam aut.\n\nQuis et veritatis quia voluptate consequatur eum et. Ab nam quidem quis ipsum eligendi quas ut nisi harum. Vel consequatur dolor iusto officia sed eum commodi magnam omnis.",
                            ProductId = new Guid("66351a09-cc05-4983-8af9-67233b51a9e6"),
                            Title = "Impedit qui eligendi nisi ipsam non beatae."
                        },
                        new
                        {
                            Id = new Guid("8e1001b4-dfd2-48f2-9a9d-45c53c249c8f"),
                            Comment = "Quia nostrum eum provident. Nobis quas et dicta vel nihil dolore magni doloremque. Error voluptatem natus unde. Velit doloremque ut esse recusandae voluptatem cupiditate. Ea enim et facilis ab.\n\nNon sint sequi perferendis est dolor ullam. Ea id similique et sit et sunt numquam suscipit. Enim consequatur qui cupiditate. Consequatur ullam molestiae nesciunt quaerat aspernatur unde. Aut et natus quaerat voluptas in similique ad nisi. Deserunt blanditiis velit qui ipsa ipsam saepe beatae.\n\nId ab tempore. Repellat provident magnam. Error ab omnis in vero dicta saepe dolorem aliquam eaque. Sit sed dolores debitis eaque laborum dolor. Corporis magnam eum ex est magnam sit.",
                            ProductId = new Guid("f4e63cbc-05f9-429d-bb06-f1c738bc35bc"),
                            Title = "Quod enim minus."
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Backpacks.Backpack", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BackpackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Backpack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39caff60-96b6-4205-9cb1-307e0462f661"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 18, 4, 12, 7, 233, DateTimeKind.Unspecified).AddTicks(5514), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Plastic Soap",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=703&blur",
                            Price = 282.71m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 4,
                            Stock = 3584,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("bf3eb5f8-d884-4c52-96ff-8fbe4529bd2c"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 18, 8, 59, 10, 163, DateTimeKind.Unspecified).AddTicks(8137), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Metal Soap",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=17&blur",
                            Price = 932.60m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 7,
                            Stock = 1499,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("b825d366-0023-4a5c-8ea8-da2057d624e8"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 9, 9, 53, 44, 841, DateTimeKind.Unspecified).AddTicks(4263), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Rubber Ball",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=323&blur",
                            Price = 878.78m,
                            ProductTypeId = new Guid("301e6738-d1db-4836-8f52-9e8b8d861661"),
                            Rating = 10,
                            Stock = 784,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("901d3139-d7a7-45ba-9ecc-66305d7963fe"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 4, 30, 20, 18, 28, 243, DateTimeKind.Unspecified).AddTicks(6779), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Small Fresh Bacon",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1011&blur",
                            Price = 250.23m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 0,
                            Stock = 434,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("8c6cadbe-8976-41a8-aa61-3605f56df5fd"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 21, 18, 27, 54, 601, DateTimeKind.Unspecified).AddTicks(3124), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Plastic Keyboard",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=995&blur",
                            Price = 638.39m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 7,
                            Stock = 4841,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("5906af6d-7d9a-439c-96ad-b5918d3bf9de"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 2, 18, 30, 51, 364, DateTimeKind.Unspecified).AddTicks(7441), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Steel Keyboard",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=983&blur",
                            Price = 143.19m,
                            ProductTypeId = new Guid("301e6738-d1db-4836-8f52-9e8b8d861661"),
                            Rating = 0,
                            Stock = 3470,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("c56b7fa4-0435-46be-a117-08aa0d64eb54"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 4, 6, 54, 41, 482, DateTimeKind.Unspecified).AddTicks(9168), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Concrete Hat",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=55&blur",
                            Price = 312.40m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 1,
                            Stock = 4635,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("f2fb341c-e8d7-4b82-acd3-e0d31b540e33"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 18, 15, 14, 41, 529, DateTimeKind.Unspecified).AddTicks(7507), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Metal Cheese",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=910&blur",
                            Price = 922.84m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 6,
                            Stock = 3606,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("8156e01c-71c4-45b1-9e30-1c0e1c12c15a"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 6, 23, 41, 27, 204, DateTimeKind.Unspecified).AddTicks(9637), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Steel Gloves",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=300&blur",
                            Price = 755.50m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 7,
                            Stock = 3571,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("f59364a4-0fa5-4d13-a5bb-3ce64fb73ce0"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 27, 4, 59, 57, 43, DateTimeKind.Unspecified).AddTicks(2323), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Cotton Table",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=808&blur",
                            Price = 884.22m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 7,
                            Stock = 4004,
                            BackpackType = "Overnight"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Boots.Boot", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BootType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Boot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("528969f7-c7be-4679-a974-b7eb9b6e9d0c"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 18, 3, 23, 41, 799, DateTimeKind.Unspecified).AddTicks(8409), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Steel Chips",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=879&blur",
                            Price = 949.71m,
                            ProductTypeId = new Guid("301e6738-d1db-4836-8f52-9e8b8d861661"),
                            Rating = 8,
                            Stock = 1935,
                            BootType = "Engineer",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("16519414-ac3b-4900-a80c-190c69859e55"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 14, 18, 13, 58, 881, DateTimeKind.Unspecified).AddTicks(703), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Fresh Ball",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=948&blur",
                            Price = 209.07m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 1,
                            Stock = 2400,
                            BootType = "Engineer",
                            Size = 22
                        },
                        new
                        {
                            Id = new Guid("4f3094ec-ec70-4f5f-b53e-7fd0801c12ab"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 2, 21, 28, 34, 791, DateTimeKind.Unspecified).AddTicks(4065), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handcrafted Rubber Chair",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=332&blur",
                            Price = 879.45m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 10,
                            Stock = 2747,
                            BootType = "Cowboy",
                            Size = 22
                        },
                        new
                        {
                            Id = new Guid("88a354e4-5e40-4ab6-a699-86d557b8710d"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 22, 20, 39, 31, 641, DateTimeKind.Unspecified).AddTicks(9244), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Metal Towels",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=927&blur",
                            Price = 478.69m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 7,
                            Stock = 709,
                            BootType = "Chelsea",
                            Size = 24
                        },
                        new
                        {
                            Id = new Guid("bd379ae6-daf4-4b70-9e30-3dd180f511d2"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 28, 16, 47, 33, 743, DateTimeKind.Unspecified).AddTicks(3908), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Rubber Cheese",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=206&blur",
                            Price = 254.07m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 5,
                            Stock = 966,
                            BootType = "Engineer",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("e5b26f70-4211-4308-b445-ee0a4a2a5f19"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 17, 10, 55, 33, 750, DateTimeKind.Unspecified).AddTicks(922), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Steel Chair",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=817&blur",
                            Price = 175.86m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 10,
                            Stock = 193,
                            BootType = "Engineer",
                            Size = 30
                        },
                        new
                        {
                            Id = new Guid("4af43ffd-b763-44ef-b030-9e166cc46fe0"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 22, 6, 33, 4, 113, DateTimeKind.Unspecified).AddTicks(677), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Granite Cheese",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=155&blur",
                            Price = 261.28m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 0,
                            Stock = 1591,
                            BootType = "Chelsea",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("e879d31d-af94-4075-848b-9b898e6d8a8c"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 22, 1, 46, 10, 679, DateTimeKind.Unspecified).AddTicks(8419), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Granite Shoes",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=260&blur",
                            Price = 882.66m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 0,
                            Stock = 4232,
                            BootType = "Drysuit",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("d3123987-8390-41e1-be0b-d0d4f578bd6a"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 4, 7, 5, 33, 54, 659, DateTimeKind.Unspecified).AddTicks(3281), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Wooden Table",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=328&blur",
                            Price = 524.59m,
                            ProductTypeId = new Guid("301e6738-d1db-4836-8f52-9e8b8d861661"),
                            Rating = 2,
                            Stock = 2371,
                            BootType = "Harness",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("43905107-13ef-4a79-83f0-f2387aab98ae"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 1, 19, 44, 55, 369, DateTimeKind.Unspecified).AddTicks(3693), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Soft Soap",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=951&blur",
                            Price = 490.50m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 8,
                            Stock = 3155,
                            BootType = "Drysuit",
                            Size = 21
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Kayaks.Kayak", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<int>("AmountOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("KayakType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kayak");

                    b.HasData(
                        new
                        {
                            Id = new Guid("efb39614-f2dc-489b-a458-e97e7bd49d60"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 12, 1, 34, 59, 49, DateTimeKind.Unspecified).AddTicks(4261), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Steel Gloves",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1080&blur",
                            Price = 86.25m,
                            ProductTypeId = new Guid("301e6738-d1db-4836-8f52-9e8b8d861661"),
                            Rating = 10,
                            Stock = 2862,
                            AmountOfPerson = 1,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("8c15793b-bdf5-4818-950b-3cad57493d93"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 27, 16, 46, 53, 906, DateTimeKind.Unspecified).AddTicks(5469), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Small Granite Salad",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=116&blur",
                            Price = 610.22m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 3,
                            Stock = 1000,
                            AmountOfPerson = 2,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("2416836c-ee63-4252-9b3d-34a28d8f86c8"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 2, 15, 18, 37, 873, DateTimeKind.Unspecified).AddTicks(115), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Plastic Soap",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=208&blur",
                            Price = 383.03m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 2,
                            Stock = 1959,
                            AmountOfPerson = 1,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("1aff9598-62dc-4fab-83fb-d4bb71bd81ee"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 29, 8, 32, 43, 234, DateTimeKind.Unspecified).AddTicks(3685), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Metal Bacon",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=7&blur",
                            Price = 864.81m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 10,
                            Stock = 1883,
                            AmountOfPerson = 1,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("d5867a40-9000-4c19-baa2-92c88c1029ed"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 7, 3, 5, 15, 333, DateTimeKind.Unspecified).AddTicks(5963), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Granite Computer",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=643&blur",
                            Price = 463.99m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 1,
                            Stock = 23,
                            AmountOfPerson = 2,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("12094de7-443d-4ebb-a887-49a01d6c5c65"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 26, 13, 11, 50, 685, DateTimeKind.Unspecified).AddTicks(5116), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Fresh Hat",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=219&blur",
                            Price = 20.93m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 6,
                            Stock = 4182,
                            AmountOfPerson = 3,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("f7db1c45-3751-4b21-af88-7fb951a7ce53"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 25, 18, 4, 14, 264, DateTimeKind.Unspecified).AddTicks(6747), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Metal Soap",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=346&blur",
                            Price = 741.22m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 10,
                            Stock = 1474,
                            AmountOfPerson = 2,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("c3d65c01-be1d-4577-8acd-cae54e37b4d3"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 20, 15, 26, 41, 917, DateTimeKind.Unspecified).AddTicks(1912), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Concrete Mouse",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=418&blur",
                            Price = 711.34m,
                            ProductTypeId = new Guid("301e6738-d1db-4836-8f52-9e8b8d861661"),
                            Rating = 0,
                            Stock = 501,
                            AmountOfPerson = 1,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("66351a09-cc05-4983-8af9-67233b51a9e6"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 24, 23, 31, 1, 614, DateTimeKind.Unspecified).AddTicks(5075), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Steel Computer",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=867&blur",
                            Price = 62.54m,
                            ProductTypeId = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119"),
                            Rating = 6,
                            Stock = 3259,
                            AmountOfPerson = 2,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("f4e63cbc-05f9-429d-bb06-f1c738bc35bc"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 1, 15, 51, 24, 697, DateTimeKind.Unspecified).AddTicks(9549), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Metal Chair",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=179&blur",
                            Price = 922.65m,
                            ProductTypeId = new Guid("3a02a977-1124-405f-a52f-978887273586"),
                            Rating = 0,
                            Stock = 1896,
                            AmountOfPerson = 2,
                            KayakType = "Racing"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeOne", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("301e6738-d1db-4836-8f52-9e8b8d861661")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeThree", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeThree");

                    b.HasData(
                        new
                        {
                            Id = new Guid("626cac8b-2c91-4f20-9bf3-72b86e31f119")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeTwo", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeTwo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a02a977-1124-405f-a52f-978887273586")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
