// <auto-generated />
using System;
using Dotnet6.GraphQL4.Store.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotnet6.GraphQL4.Store.Repositories.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20210502210750_First migration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("IntroduceAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff73782b-2017-41bc-8461-a77cfea4ac9c"),
                            Comment = "Itaque voluptatem consectetur similique velit qui harum sed nihil. Et voluptatibus illum neque similique qui odit minima non. Fugit quisquam consequuntur similique minus.\n\nEst voluptatem similique dicta in libero. Officiis quod aperiam inventore sed voluptatem qui sed et. Nostrum totam ut qui reiciendis dolorem eius quod consequuntur. Quisquam inventore minus et itaque omnis.\n\nConsequatur explicabo ab at sit ipsam et aliquam unde. Neque quam commodi atque sapiente ea hic ullam consequatur eveniet. Dolorem aut eveniet nesciunt natus.",
                            ProductId = new Guid("abf8d8cc-b09f-43e9-be52-0b512aa71f1d"),
                            Title = "Quae beatae unde iste ea quod."
                        },
                        new
                        {
                            Id = new Guid("1657b078-c145-4c26-9136-2c999c5d1eda"),
                            Comment = "Accusamus rem suscipit. Sapiente reprehenderit maxime voluptatum sit. Saepe quam voluptas ipsa nostrum nulla. Accusantium neque laudantium dolores.\n\nDolorem ut repellendus. Quia ut aspernatur. Vitae excepturi quisquam rerum voluptatem tempore. At quia beatae. Rem et rerum ut et sunt omnis illo eveniet molestiae. Culpa asperiores beatae sapiente minima delectus ex delectus.\n\nDoloribus natus vitae. Eveniet voluptates assumenda praesentium. Voluptas eos nemo est laboriosam iure repellat laudantium excepturi blanditiis.",
                            ProductId = new Guid("1b946a7e-b43a-4434-8d0e-7eaab2d032b3"),
                            Title = "Ducimus incidunt voluptatem aliquid omnis consequuntur sunt."
                        },
                        new
                        {
                            Id = new Guid("c82a47d8-1c43-4c71-b343-64ce0cd4e80f"),
                            Comment = "Dolor esse nam nulla. Porro dolores eum mollitia nostrum dolores amet quam. Ullam dicta temporibus aperiam vel aperiam aliquam. Deserunt et voluptates aut corrupti recusandae impedit commodi.\n\nTemporibus quis harum culpa qui delectus reiciendis. Fugit voluptates a. Dolores fuga eum.\n\nEa temporibus magni dolores officiis rerum dolorum. Quis atque et ea natus expedita. Placeat quia reprehenderit natus itaque voluptates similique et alias a. Adipisci tenetur quasi maxime sunt fugit.",
                            ProductId = new Guid("dfd7c6cb-99de-434d-9ffd-c3f81a633d6d"),
                            Title = "Eum labore provident culpa omnis sequi ullam quia aut."
                        },
                        new
                        {
                            Id = new Guid("07146e83-6ef0-42e8-b0db-741a9b190c9e"),
                            Comment = "Qui vitae deleniti est. Accusantium et et aspernatur assumenda perspiciatis animi culpa. Neque fugit rerum eius molestiae delectus rerum.\n\nIllo tenetur voluptatem eligendi magni eligendi. Quod atque deleniti vero ratione voluptatem qui ut exercitationem. Eos quasi iure autem ea accusamus.\n\nVoluptatem et rerum cupiditate voluptatem consequuntur in quidem. Aut dolorem inventore quo voluptates perferendis omnis et et. Repellat nam architecto fuga. Voluptas repudiandae necessitatibus dignissimos. Autem dolorem architecto. Aliquam et exercitationem nulla facere sequi quis eligendi.",
                            ProductId = new Guid("ba41753d-3f58-43c1-9657-4468da506538"),
                            Title = "Et quos atque provident aut fugiat perferendis consequatur et quia."
                        },
                        new
                        {
                            Id = new Guid("e1ae6ed9-9b12-42e4-a90e-a16432051aae"),
                            Comment = "Officia dicta illo quis ad. Tenetur quod dolorum. Libero hic aut nihil voluptatem sed et beatae. Autem assumenda vel qui. Possimus neque enim nulla harum dolor aut numquam aut. Et similique perspiciatis cupiditate excepturi quam perferendis quia ut.\n\nNesciunt molestiae eius excepturi voluptatem cum. Sapiente deserunt ducimus aliquid voluptate sit. Distinctio animi alias. Doloribus autem est voluptatem aut rerum ratione quas.\n\nQui veniam aut sequi est ut quia commodi. Hic et esse. Quidem officiis assumenda sapiente alias ducimus et. Omnis perferendis est officiis.",
                            ProductId = new Guid("8fb4b6c3-52dd-4041-91b0-945df91daf04"),
                            Title = "Soluta fuga tenetur libero aut est illum."
                        },
                        new
                        {
                            Id = new Guid("8582dff6-6dd5-4d88-8e0b-543cc9f6d51a"),
                            Comment = "Itaque veritatis ut rem. Aspernatur occaecati quaerat. Nemo laboriosam est dolor soluta laudantium. Repellat ipsa eum.\n\nAccusamus quibusdam itaque. Dolor nemo error quis incidunt aliquam ipsam praesentium aliquid. Ipsam qui quis consectetur sequi. Cupiditate earum est inventore sit fugit praesentium debitis consequatur. Et explicabo quos aut aut.\n\nEst error eius eum eos a magnam. Tempora doloremque nihil quis dicta. Quidem quia aliquam voluptate ut accusantium blanditiis aut laudantium eaque. Ut tempora nesciunt. Dolorem temporibus nihil dicta error dolor.",
                            ProductId = new Guid("89b9fbaf-1a0d-4e71-8c21-a86d52d6ec76"),
                            Title = "Atque quos et vitae dignissimos sequi rerum earum."
                        },
                        new
                        {
                            Id = new Guid("6f9206a4-7308-43ba-94b3-a21eb8b752a8"),
                            Comment = "Dolorem distinctio consequatur tempore unde dolores optio molestiae non. Dolor reiciendis non nemo dignissimos quam molestiae et. Atque eius odit mollitia sunt error praesentium aut velit soluta.\n\nFuga minima hic facilis architecto omnis numquam voluptatum quidem eius. Voluptatem amet illum omnis illo in dolores earum. Maiores consequatur molestiae animi. Nihil omnis et voluptatibus ut in tenetur a eum fuga.\n\nNobis nobis qui enim dolores omnis sed non a. Autem nihil molestiae eveniet assumenda quo veniam minus doloremque neque. Officia aut sint ipsa autem excepturi repudiandae ut. Explicabo nisi et repellat consequuntur est corrupti quae iste. Nemo incidunt officia amet omnis alias et. Rerum ipsa nesciunt sapiente facere ex quia sit ad.",
                            ProductId = new Guid("8f0c19d5-ce5a-4ac8-a698-84a080ad33b0"),
                            Title = "Ut beatae cupiditate dolores."
                        },
                        new
                        {
                            Id = new Guid("73cf0774-58f4-4490-abe2-f1a97c6d74c2"),
                            Comment = "Eius fugiat non architecto at porro voluptas. Distinctio deleniti similique omnis eligendi rerum natus vitae. Dolorem facere et. Dolorem maiores et assumenda. Quibusdam repellendus sed quis ut eos quo molestiae modi aliquid. Modi aut omnis voluptatum et dolores corporis.\n\nEt eaque ut et amet voluptatem repudiandae culpa ut. Ullam qui assumenda illo magni tempore atque natus nisi. Temporibus consequuntur aliquid eveniet atque iste. Reiciendis voluptatum velit voluptatibus sapiente explicabo veniam nulla. Esse explicabo commodi est porro eos sit dicta molestiae quod.\n\nLaboriosam est nostrum. Mollitia dolorum enim et. Dolorem omnis quaerat. Repudiandae aut iusto voluptatem enim maxime nihil. Eius explicabo deleniti perferendis voluptas.",
                            ProductId = new Guid("64cbbffb-4312-4679-bdea-eb98a7330d9e"),
                            Title = "Vitae corrupti culpa."
                        },
                        new
                        {
                            Id = new Guid("13c1475a-c8b0-40ad-8216-211bb8e70b95"),
                            Comment = "Et quod sed. Ut qui ut qui omnis. Eius qui possimus et nisi at. Architecto temporibus nisi impedit similique aliquam quia sit sunt.\n\nEa itaque eum quasi. Cum vel aut. Facilis tenetur provident. Omnis ullam commodi et numquam voluptates accusamus quibusdam. Omnis tempore rerum omnis. Molestiae soluta eum et perferendis commodi voluptatibus.\n\nNon qui et molestiae non sed culpa eos ut eos. Est quam repellat id. Velit ut architecto nam qui.",
                            ProductId = new Guid("35328f4f-d922-47b2-8312-1b9c73899019"),
                            Title = "Voluptas porro totam et."
                        },
                        new
                        {
                            Id = new Guid("a8a3d4e2-c898-4d52-b31d-36d251846520"),
                            Comment = "Voluptas optio in saepe sint dolores consequatur quaerat. Harum vitae voluptas deserunt quam debitis reiciendis. Magnam sit accusantium et blanditiis. Ipsa soluta illum et sed.\n\nEt inventore illum aut tenetur cupiditate. Est voluptatem repudiandae aut. Consequatur nihil fugit fuga rerum tenetur veritatis quibusdam. Doloribus quis architecto aut omnis ex molestias natus voluptas unde. Voluptatem quis rem ut in eos ea. Minus aut consequuntur ullam numquam ex nisi.\n\nVelit voluptas nesciunt numquam error est non. Ut est harum doloribus. Corporis cum veniam.",
                            ProductId = new Guid("95a7f6c3-c9fd-4350-9e84-a4e7c01fbaf7"),
                            Title = "Aut placeat numquam dignissimos omnis est voluptas amet iure."
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Backpacks.Backpack", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BackpackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Backpack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b02bdec-cb56-4bc4-a52c-d2fa5b04dba5"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 17, 20, 22, 15, 232, DateTimeKind.Unspecified).AddTicks(6774), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Fresh Tuna",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=534&blur",
                            Price = 135.05m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 7,
                            Stock = 3439,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("1f0094d2-f07d-499e-9af8-f0d9fca71e8d"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 19, 6, 36, 25, 685, DateTimeKind.Unspecified).AddTicks(7346), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Concrete Fish",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=110&blur",
                            Price = 478.42m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 4,
                            Stock = 3616,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("5a0da657-2b0a-4db3-9cc6-df74efab41c0"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 22, 23, 41, 17, 581, DateTimeKind.Unspecified).AddTicks(475), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Metal Keyboard",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=694&blur",
                            Price = 45.09m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 3,
                            Stock = 4464,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("1c9ac255-e4f3-4732-ab59-cdf3f1b2adfa"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 2, 14, 50, 13, 919, DateTimeKind.Unspecified).AddTicks(8848), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Fresh Bike",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=441&blur",
                            Price = 18.41m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 6,
                            Stock = 470,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("3b10cea2-7138-4937-ab79-7114edfcda96"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 21, 19, 21, 50, 642, DateTimeKind.Unspecified).AddTicks(7884), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Steel Salad",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=221&blur",
                            Price = 465.38m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 5,
                            Stock = 2009,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("fdecd675-c6c5-4ec1-895c-2b40696278b1"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 10, 11, 1, 13, 684, DateTimeKind.Unspecified).AddTicks(9676), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Wooden Mouse",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=407&blur",
                            Price = 995.24m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 1,
                            Stock = 4240,
                            BackpackType = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("71d5c4a2-8b60-4d78-b021-f80e2612faec"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 27, 23, 47, 35, 505, DateTimeKind.Unspecified).AddTicks(4669), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Frozen Pants",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=857&blur",
                            Price = 813.69m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 0,
                            Stock = 1251,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("e5e6ae11-7aab-4e3e-a9d6-cf74c95394ed"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 27, 21, 35, 25, 266, DateTimeKind.Unspecified).AddTicks(4098), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Generic Soft Hat",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=852&blur",
                            Price = 15.33m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 7,
                            Stock = 2552,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("77809ee9-1cde-4487-9e77-fc419e6f0bae"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 23, 9, 30, 13, 508, DateTimeKind.Unspecified).AddTicks(847), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Plastic Cheese",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=149&blur",
                            Price = 390.52m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 6,
                            Stock = 2696,
                            BackpackType = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("7c720012-fec9-42e0-9f0c-92a45ea192b1"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 14, 17, 31, 42, 733, DateTimeKind.Unspecified).AddTicks(7192), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Soft Pizza",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=556&blur",
                            Price = 481.66m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 10,
                            Stock = 4786,
                            BackpackType = "Cycling"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Boots.Boot", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BootType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Boot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e24d70a4-4d8d-4116-b18c-d685fd16b51f"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 17, 22, 25, 22, 646, DateTimeKind.Unspecified).AddTicks(5758), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Fantastic Granite Cheese",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=677&blur",
                            Price = 580.79m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 7,
                            Stock = 3912,
                            BootType = "Engineer",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("e387d182-295e-4f58-901b-3a6552949fd6"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 14, 15, 40, 38, 510, DateTimeKind.Unspecified).AddTicks(1741), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Cotton Sausages",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=662&blur",
                            Price = 389.76m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 4,
                            Stock = 709,
                            BootType = "Drysuit",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("8f5ade1b-6c0e-4efd-9de9-c500f4a757cd"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 21, 7, 11, 44, 442, DateTimeKind.Unspecified).AddTicks(9294), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Fantastic Rubber Bike",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=915&blur",
                            Price = 677.49m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 5,
                            Stock = 294,
                            BootType = "Cowboy",
                            Size = 30
                        },
                        new
                        {
                            Id = new Guid("8b1413ca-7cfb-4f3a-9360-722c53263bfa"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 27, 5, 58, 21, 977, DateTimeKind.Unspecified).AddTicks(3471), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Cotton Cheese",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1084&blur",
                            Price = 127.87m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 6,
                            Stock = 3944,
                            BootType = "Cowboy",
                            Size = 23
                        },
                        new
                        {
                            Id = new Guid("dc0906dd-71bf-4fe1-90a0-209930bff579"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 7, 15, 19, 24, 788, DateTimeKind.Unspecified).AddTicks(3221), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Fresh Hat",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=563&blur",
                            Price = 930.05m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 6,
                            Stock = 4309,
                            BootType = "Drysuit",
                            Size = 22
                        },
                        new
                        {
                            Id = new Guid("d5377eff-4f5d-4fba-ad0e-59b2957350ba"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 16, 5, 26, 30, 558, DateTimeKind.Unspecified).AddTicks(4617), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Fantastic Concrete Ball",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=233&blur",
                            Price = 903.37m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 0,
                            Stock = 2436,
                            BootType = "Drysuit",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("975f225e-6722-4b0f-b3aa-681b5ba04e28"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 10, 10, 38, 35, 490, DateTimeKind.Unspecified).AddTicks(4553), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Metal Keyboard",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=386&blur",
                            Price = 235.43m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 3,
                            Stock = 7,
                            BootType = "Cowboy",
                            Size = 23
                        },
                        new
                        {
                            Id = new Guid("6149432e-e0df-439c-90c1-a0c074c74626"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 27, 23, 29, 8, 306, DateTimeKind.Unspecified).AddTicks(6549), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Granite Cheese",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=872&blur",
                            Price = 761.04m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 4,
                            Stock = 2583,
                            BootType = "Chelsea",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("b438849a-06d1-40cd-9610-ddb4f5378a6b"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 29, 3, 56, 29, 3, DateTimeKind.Unspecified).AddTicks(7672), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Fresh Pizza",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=349&blur",
                            Price = 914.05m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 5,
                            Stock = 2944,
                            BootType = "Chelsea",
                            Size = 29
                        },
                        new
                        {
                            Id = new Guid("e535d1ec-2820-46c5-8b7a-7186054569c3"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 16, 3, 37, 36, 495, DateTimeKind.Unspecified).AddTicks(312), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Metal Table",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=318&blur",
                            Price = 301.97m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 7,
                            Stock = 2454,
                            BootType = "Chelsea",
                            Size = 26
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Kayaks.Kayak", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<int>("AmountOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("KayakType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kayak");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abf8d8cc-b09f-43e9-be52-0b512aa71f1d"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 21, 10, 58, 22, 429, DateTimeKind.Unspecified).AddTicks(4172), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Fantastic Metal Towels",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=277&blur",
                            Price = 177.90m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 5,
                            Stock = 4888,
                            AmountOfPerson = 1,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("1b946a7e-b43a-4434-8d0e-7eaab2d032b3"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 17, 22, 29, 57, 581, DateTimeKind.Unspecified).AddTicks(13), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Concrete Mouse",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=978&blur",
                            Price = 324.40m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 5,
                            Stock = 2956,
                            AmountOfPerson = 3,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("dfd7c6cb-99de-434d-9ffd-c3f81a633d6d"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 20, 6, 35, 28, 823, DateTimeKind.Unspecified).AddTicks(7052), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Generic Concrete Mouse",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=908&blur",
                            Price = 117.70m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 1,
                            Stock = 4904,
                            AmountOfPerson = 2,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("ba41753d-3f58-43c1-9657-4468da506538"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 18, 7, 21, 33, 812, DateTimeKind.Unspecified).AddTicks(3172), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Rubber Tuna",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=329&blur",
                            Price = 66.33m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 3,
                            Stock = 4004,
                            AmountOfPerson = 2,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("8fb4b6c3-52dd-4041-91b0-945df91daf04"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 17, 16, 4, 53, 408, DateTimeKind.Unspecified).AddTicks(9094), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Fresh Table",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=972&blur",
                            Price = 491.57m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 1,
                            Stock = 4022,
                            AmountOfPerson = 1,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("89b9fbaf-1a0d-4e71-8c21-a86d52d6ec76"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 4, 11, 42, 14, 605, DateTimeKind.Unspecified).AddTicks(2072), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Soft Mouse",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=102&blur",
                            Price = 636.00m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 4,
                            Stock = 4335,
                            AmountOfPerson = 2,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("8f0c19d5-ce5a-4ac8-a698-84a080ad33b0"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 27, 8, 6, 9, 827, DateTimeKind.Unspecified).AddTicks(5518), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Generic Plastic Bacon",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=539&blur",
                            Price = 68.84m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 7,
                            Stock = 434,
                            AmountOfPerson = 2,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("64cbbffb-4312-4679-bdea-eb98a7330d9e"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 30, 5, 40, 11, 765, DateTimeKind.Unspecified).AddTicks(3851), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Concrete Bike",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=861&blur",
                            Price = 139.21m,
                            ProductTypeId = new Guid("637d058e-069b-4df5-801c-208af77ff6b6"),
                            Rating = 0,
                            Stock = 4810,
                            AmountOfPerson = 1,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("35328f4f-d922-47b2-8312-1b9c73899019"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 4, 7, 7, 33, 6, 515, DateTimeKind.Unspecified).AddTicks(3250), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Metal Hat",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=826&blur",
                            Price = 69.32m,
                            ProductTypeId = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd"),
                            Rating = 4,
                            Stock = 4017,
                            AmountOfPerson = 2,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("95a7f6c3-c9fd-4350-9e84-a4e7c01fbaf7"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 4, 29, 1, 12, 18, 622, DateTimeKind.Unspecified).AddTicks(3443), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Granite Hat",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1058&blur",
                            Price = 200.46m,
                            ProductTypeId = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593"),
                            Rating = 3,
                            Stock = 747,
                            AmountOfPerson = 1,
                            KayakType = "Diving"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeOne", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("637d058e-069b-4df5-801c-208af77ff6b6")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeThree", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeThree");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d411d30d-0ccd-458c-8243-0fb9d5073dcd")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeTwo", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeTwo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57e845ca-1e94-4ffa-8f73-9dc4e1274593")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
