// <auto-generated />
using System;
using Dotnet6.GraphQL4.Store.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotnet6.GraphQL4.Store.Repositories.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20210502214215_First migration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("IntroduceAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("812c2286-449c-49c2-a7ff-1ea54ad2dbec"),
                            Comment = "Qui perferendis dolores in laboriosam sit sint nulla dolor magnam. Odio qui saepe nam et veniam. Sit repellat et eos dicta nisi sint voluptas eius. Assumenda voluptatem repudiandae sed ad temporibus molestiae animi nisi dolorem. Repellat corrupti expedita rerum necessitatibus voluptatum labore et sint.\n\nQuo quod officia itaque est. Dolorem non qui sit adipisci maxime rem ut. Impedit animi cum corrupti.\n\nConsectetur molestiae enim et veniam odio occaecati amet est voluptate. Non ratione autem. Fuga et quas unde amet sequi accusamus dolor fuga. Dicta ab libero magni qui ut sit.",
                            ProductId = new Guid("414d6a4c-e1a8-4954-8ebb-ff52a7a80235"),
                            Title = "Totam temporibus totam eaque ut tempore repudiandae."
                        },
                        new
                        {
                            Id = new Guid("2729ee8e-4160-46ea-b68f-508bb5570bc9"),
                            Comment = "Deleniti odio facere dolores quae sunt ipsam. Odio deserunt voluptates corrupti dolorum totam quis et incidunt eius. Voluptas optio accusantium vero eum. Consequatur et nesciunt.\n\nUt praesentium commodi commodi nostrum non beatae sunt delectus nihil. Repudiandae a consequuntur impedit. Quibusdam magnam voluptate asperiores perferendis atque et sequi. Cumque quibusdam dolor aut officiis. Debitis mollitia nostrum ea qui ut ratione. Delectus ea ea nulla minus sed saepe.\n\nVelit vel quo quo voluptatem tempore corrupti et. Beatae et sunt ut doloremque provident necessitatibus qui veniam dignissimos. Dolore voluptatibus numquam. Dolorem et reiciendis dolore et et. Assumenda debitis laborum non ipsum. Est perferendis omnis suscipit rerum.",
                            ProductId = new Guid("daad337a-6761-4022-ba07-9717de42d19e"),
                            Title = "Vero sit mollitia occaecati."
                        },
                        new
                        {
                            Id = new Guid("9f4ae24b-3705-4b15-a8f1-f4f4ef3c391b"),
                            Comment = "Qui ea non dolore a aliquam. Voluptate est optio voluptatem sapiente excepturi itaque consequatur. Ratione saepe quo delectus accusantium. In illo quia impedit iste aut non id accusamus. Amet quia veniam nihil in fugit.\n\nQuos illo error aut nihil amet magni quas ut corrupti. Occaecati aut nihil ut odio placeat deleniti reiciendis. Fugiat animi dolor corporis molestias numquam tempore veritatis. Laboriosam quos illum eum. Voluptates qui exercitationem vel suscipit iusto molestiae magni. Facilis aut voluptatem rerum.\n\nDeserunt et et et. Tempora quia autem soluta voluptates vero. Voluptate dolores maiores dolores. Quo reiciendis omnis reiciendis. Omnis ducimus sed voluptas quis saepe nobis.",
                            ProductId = new Guid("ad5fd707-1f4b-494c-b77a-8d19012477ca"),
                            Title = "Sapiente dolores et et."
                        },
                        new
                        {
                            Id = new Guid("d1f502af-5860-4121-9945-4f24c5fcadb8"),
                            Comment = "Vero autem facilis quibusdam enim saepe. Ullam illo praesentium quia et aut. Itaque qui ipsum et temporibus nihil excepturi quas. Sunt occaecati vel. Autem ex porro dolorum suscipit quibusdam dignissimos culpa ullam. Laborum ad dolorem blanditiis.\n\nReiciendis qui tempore reprehenderit optio ab est sit quia. Quisquam quidem ipsum sit sit voluptas aut veritatis dolor. Soluta temporibus dolorum.\n\nItaque modi hic dolore in. Et minus repudiandae soluta tempora quae sit dolores quidem. Voluptate magni temporibus atque est nemo exercitationem illum suscipit beatae.",
                            ProductId = new Guid("b18aba7c-f135-4ada-8576-38b5a0acf974"),
                            Title = "Accusantium omnis cumque et placeat quam fugit."
                        },
                        new
                        {
                            Id = new Guid("e5287afb-acb9-4873-9c50-caf0ed76cfea"),
                            Comment = "Est molestiae aut aut ad. Sit facilis molestias nobis delectus nesciunt consectetur modi. Pariatur et et. Numquam porro rerum in qui. Qui amet quis. Consequuntur vitae alias iure mollitia voluptatem exercitationem qui.\n\nConsequatur quasi possimus natus sint deserunt. Commodi consequatur ad eligendi sit libero sunt eum magnam. Dolore tenetur nisi et. Neque ut itaque qui perferendis dolorum fuga hic.\n\nAperiam consequatur temporibus eum vel recusandae maxime vitae aut. Assumenda est illo dolorem. Occaecati inventore ipsam cumque. Mollitia quo omnis nisi repellendus veniam porro repellat. Corporis consequuntur earum quia nostrum ratione. Eveniet rerum rem qui.",
                            ProductId = new Guid("d3fca6f7-ed4f-4b9b-ad99-142ca5e95dd9"),
                            Title = "Excepturi ab voluptate."
                        },
                        new
                        {
                            Id = new Guid("5c6c55a9-5c5d-4214-8f97-5e5c41436753"),
                            Comment = "Hic ullam repellat doloremque est perferendis corrupti sit nesciunt hic. Sit nemo laborum. Velit ab culpa et quaerat delectus. Non laudantium sapiente dolorem ab omnis.\n\nUt suscipit voluptatum omnis occaecati dolorem. Sed molestias quod. Quos dolorum omnis iusto quisquam dicta quasi et quis. Et suscipit temporibus sapiente iste maxime nulla sunt iste cupiditate. Praesentium dignissimos libero maiores nobis et.\n\nNulla officiis veniam. Ut ea perferendis quia quod. Totam molestias error repellat. Ad ut quis quia et voluptate consequatur sit.",
                            ProductId = new Guid("b9145011-9f69-4fea-9ef4-71fb913fd8fc"),
                            Title = "Tempora quia repellendus."
                        },
                        new
                        {
                            Id = new Guid("be47a10d-64c8-4170-941c-6adf31558140"),
                            Comment = "Adipisci quae nemo excepturi ducimus voluptate aut voluptas voluptatem adipisci. Ut eos natus fugiat ut commodi ex id aut et. Est quae deserunt quaerat inventore aperiam. Et dolores ipsa architecto reprehenderit ipsa amet non. Culpa ut vero laudantium dolores ullam dignissimos. Dolorum ut quam.\n\nAmet neque adipisci. In aut in. Voluptas dolor doloribus aut beatae debitis officiis dolores. Facere assumenda ut rerum debitis consequatur laudantium. Eius quidem quos reiciendis et consequatur placeat in doloribus.\n\nLaborum distinctio at officiis minima labore quis culpa. Quos eveniet sint quisquam aspernatur et non temporibus. Corrupti ea dolor tenetur asperiores sit omnis. Aut voluptate veniam tempore quia possimus et provident ipsum aut.",
                            ProductId = new Guid("fc4edcd6-7412-49be-8d96-296a4b399a8e"),
                            Title = "Nostrum sunt molestiae illo."
                        },
                        new
                        {
                            Id = new Guid("45419636-f0c1-41ed-8315-1c2e260afda4"),
                            Comment = "Tempore sint minus similique in velit fugit magni iure numquam. Vitae neque saepe pariatur voluptas. Saepe earum ut vitae autem. Eius consequuntur recusandae omnis expedita. Suscipit dolores et repellat natus adipisci explicabo iste eligendi.\n\nAnimi id molestiae ab quae. Voluptatum quae voluptate aut ipsa a. Dolorum quia dignissimos aut est quibusdam maxime.\n\nPorro provident iste sunt sint ea fugit et tempore. Ut ipsam deserunt neque molestiae aspernatur iusto mollitia nisi. Sunt quae libero minima inventore labore qui. Et repudiandae velit dignissimos. Sed in cupiditate quasi praesentium dignissimos ipsum quisquam veniam vel.",
                            ProductId = new Guid("e0163b62-59d2-4fb5-92ee-8cefd8687b93"),
                            Title = "Quo similique commodi soluta expedita optio quis veniam est iusto."
                        },
                        new
                        {
                            Id = new Guid("c5173bff-2f21-425f-9608-b2d1fd388a31"),
                            Comment = "Eum sapiente et voluptatem corporis similique non veritatis amet vel. Eos exercitationem corrupti illum quidem quia voluptatem. Deleniti ratione optio. Optio qui aliquid repellat sed culpa. Ea blanditiis eveniet dolores aut qui aut. Sit qui voluptas quis fugit ipsa fugit est voluptates.\n\nQuas vero est sit modi animi ut. Facere non ab. Autem quis et quas tempora enim optio aspernatur quis.\n\nSint suscipit illum dolor sequi eos. Vel tempore dolores et ut totam cumque non maiores itaque. Quas laborum minus sint voluptates molestias reprehenderit sit. Nihil laborum et minus placeat aut aut nisi. Cumque minima eveniet qui est blanditiis voluptas unde nihil. Quis quos fuga dolores.",
                            ProductId = new Guid("18a4ea4e-0c2b-493a-a0cf-6f1ea30a61b6"),
                            Title = "Adipisci id dignissimos."
                        },
                        new
                        {
                            Id = new Guid("222ae5ad-574e-493b-aa27-d20c14529f08"),
                            Comment = "Aut ut eveniet optio odio ipsam iure at earum praesentium. Inventore delectus et iusto porro doloribus aut iusto. Sunt voluptates iste sint quis voluptatem et eos magni. Natus ipsam officiis harum aliquid. Non rerum omnis ullam et perferendis quasi ut. Voluptatem dignissimos ullam fugiat dolor.\n\nNon ut aut consequatur. Est temporibus aut eaque ex laborum rerum voluptas quos. Velit sequi voluptas.\n\nEveniet cupiditate explicabo magni ducimus numquam ratione. Fugiat earum laborum eligendi quis. Ducimus dignissimos occaecati ipsum et et vel dolores veniam nihil. Voluptas voluptas quia amet quia et et. Voluptates sit possimus harum officia ducimus vel.",
                            ProductId = new Guid("5e73023d-d64f-4fe7-ad5a-5088c43bf624"),
                            Title = "Quia magnam aliquid atque eaque mollitia ducimus."
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Backpacks.Backpack", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BackpackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Backpack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ed299fd-42df-4496-bcd7-aef4047302f7"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 21, 13, 21, 42, 737, DateTimeKind.Unspecified).AddTicks(8406), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Steel Ball",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=447&blur",
                            Price = 444.15m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 8,
                            Stock = 3190,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("0230cce1-1742-4b07-9db1-664bc9c66eb2"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 16, 11, 43, 39, 710, DateTimeKind.Unspecified).AddTicks(7882), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Frozen Bacon",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=227&blur",
                            Price = 776.75m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 5,
                            Stock = 882,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("b7c45bb6-24a1-4a4f-99ab-5e7d44a9822f"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 18, 6, 58, 9, 409, DateTimeKind.Unspecified).AddTicks(7453), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Plastic Pants",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=147&blur",
                            Price = 421.32m,
                            ProductTypeId = new Guid("3a1f0f73-2cd2-48a4-b343-d7df28b5387b"),
                            Rating = 7,
                            Stock = 2377,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("43e0733b-5672-4c76-a2e7-4d1d3cc68182"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 24, 11, 44, 30, 701, DateTimeKind.Unspecified).AddTicks(5852), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Plastic Chicken",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=3&blur",
                            Price = 881.88m,
                            ProductTypeId = new Guid("3a1f0f73-2cd2-48a4-b343-d7df28b5387b"),
                            Rating = 5,
                            Stock = 347,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("f2e219df-a2e1-4ed1-8c31-bf89588ce3f3"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 2, 4, 39, 11, 281, DateTimeKind.Unspecified).AddTicks(2687), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Plastic Cheese",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=272&blur",
                            Price = 476.66m,
                            ProductTypeId = new Guid("3a1f0f73-2cd2-48a4-b343-d7df28b5387b"),
                            Rating = 9,
                            Stock = 1579,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("ef82c6fc-569d-43a3-9714-f20a962fd669"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 6, 12, 48, 37, 577, DateTimeKind.Unspecified).AddTicks(1148), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Generic Fresh Ball",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=730&blur",
                            Price = 569.02m,
                            ProductTypeId = new Guid("3a1f0f73-2cd2-48a4-b343-d7df28b5387b"),
                            Rating = 1,
                            Stock = 1430,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("ffbdbe41-131c-425a-8eca-9585492f3913"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 8, 17, 57, 54, 362, DateTimeKind.Unspecified).AddTicks(8545), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Small Granite Fish",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1055&blur",
                            Price = 395.43m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 6,
                            Stock = 219,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("fb463c8d-9d4f-42eb-8c4b-d69944c1bd35"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 25, 2, 2, 32, 168, DateTimeKind.Unspecified).AddTicks(2933), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Fresh Keyboard",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=447&blur",
                            Price = 472.24m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 4,
                            Stock = 1938,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("3f9062b0-1c34-4ddc-a280-23662e67c0db"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 12, 10, 46, 31, 973, DateTimeKind.Unspecified).AddTicks(1959), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Concrete Bacon",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=650&blur",
                            Price = 355.70m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 8,
                            Stock = 910,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("a682d821-1770-4595-98a9-f5f6d4e7a50c"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 3, 1, 8, 11, 214, DateTimeKind.Unspecified).AddTicks(7356), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Cotton Gloves",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=712&blur",
                            Price = 64.28m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 3,
                            Stock = 200,
                            BackpackType = "Overnight"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Boots.Boot", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BootType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Boot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53e062d2-9143-451e-ace6-c47b4623d1e2"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 10, 10, 9, 47, 12, DateTimeKind.Unspecified).AddTicks(9922), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Cotton Table",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1023&blur",
                            Price = 731.27m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 6,
                            Stock = 4310,
                            BootType = "Engineer",
                            Size = 24
                        },
                        new
                        {
                            Id = new Guid("50d64371-7cf7-4d9a-b5c5-ca43711b90e2"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 24, 3, 40, 35, 581, DateTimeKind.Unspecified).AddTicks(1409), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Fresh Keyboard",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=574&blur",
                            Price = 722.06m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 6,
                            Stock = 901,
                            BootType = "Harness",
                            Size = 27
                        },
                        new
                        {
                            Id = new Guid("a8333c47-6769-4c75-a8ea-5f2f421228d2"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 5, 22, 26, 31, 313, DateTimeKind.Unspecified).AddTicks(2757), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Plastic Gloves",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=308&blur",
                            Price = 889.90m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 8,
                            Stock = 219,
                            BootType = "Cowboy",
                            Size = 27
                        },
                        new
                        {
                            Id = new Guid("77077e9d-7099-43b8-8f96-57e97bc52de2"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 7, 4, 45, 12, 234, DateTimeKind.Unspecified).AddTicks(1139), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Soft Towels",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=574&blur",
                            Price = 894.39m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 10,
                            Stock = 2789,
                            BootType = "Engineer",
                            Size = 22
                        },
                        new
                        {
                            Id = new Guid("046a976d-9a2c-4617-955c-d83480745d34"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 17, 9, 31, 19, 208, DateTimeKind.Unspecified).AddTicks(2974), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Cotton Car",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=857&blur",
                            Price = 230.38m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 4,
                            Stock = 4356,
                            BootType = "Football",
                            Size = 27
                        },
                        new
                        {
                            Id = new Guid("7a72861a-479e-40ae-b8d4-7a9b1e152a2a"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 6, 11, 0, 29, 810, DateTimeKind.Unspecified).AddTicks(5968), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Soft Pizza",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=626&blur",
                            Price = 28.78m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 2,
                            Stock = 4727,
                            BootType = "Chelsea",
                            Size = 24
                        },
                        new
                        {
                            Id = new Guid("47fb309e-8245-4618-8498-59ec9b8978b1"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 13, 17, 19, 33, 324, DateTimeKind.Unspecified).AddTicks(7319), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Frozen Fish",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=717&blur",
                            Price = 442.96m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 8,
                            Stock = 2110,
                            BootType = "Chelsea",
                            Size = 29
                        },
                        new
                        {
                            Id = new Guid("dc1ad637-d68b-459c-9fd6-7a86c406f594"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 5, 21, 38, 54, 263, DateTimeKind.Unspecified).AddTicks(9306), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Fresh Towels",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=240&blur",
                            Price = 588.93m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 0,
                            Stock = 2169,
                            BootType = "Harness",
                            Size = 22
                        },
                        new
                        {
                            Id = new Guid("6b70c11d-99f1-48d9-832b-c26f70ba16f3"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 25, 8, 33, 37, 413, DateTimeKind.Unspecified).AddTicks(559), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Fresh Soap",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=392&blur",
                            Price = 940.50m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 8,
                            Stock = 4042,
                            BootType = "Cowboy",
                            Size = 30
                        },
                        new
                        {
                            Id = new Guid("009cb5a5-6114-4e34-9513-fe04777a6910"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 22, 13, 43, 1, 828, DateTimeKind.Unspecified).AddTicks(4381), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Metal Chair",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=90&blur",
                            Price = 322.81m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 0,
                            Stock = 12,
                            BootType = "Engineer",
                            Size = 26
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Kayaks.Kayak", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<int>("AmountOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("KayakType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kayak");

                    b.HasData(
                        new
                        {
                            Id = new Guid("414d6a4c-e1a8-4954-8ebb-ff52a7a80235"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 28, 12, 46, 50, 237, DateTimeKind.Unspecified).AddTicks(391), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Granite Cheese",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=476&blur",
                            Price = 393.53m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 2,
                            Stock = 4493,
                            AmountOfPerson = 3,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("daad337a-6761-4022-ba07-9717de42d19e"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 17, 22, 28, 13, 546, DateTimeKind.Unspecified).AddTicks(9277), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handcrafted Steel Table",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=434&blur",
                            Price = 663.72m,
                            ProductTypeId = new Guid("3a1f0f73-2cd2-48a4-b343-d7df28b5387b"),
                            Rating = 4,
                            Stock = 4932,
                            AmountOfPerson = 1,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("ad5fd707-1f4b-494c-b77a-8d19012477ca"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 9, 19, 50, 22, 394, DateTimeKind.Unspecified).AddTicks(652), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Fresh Keyboard",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=130&blur",
                            Price = 65.31m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 7,
                            Stock = 1385,
                            AmountOfPerson = 2,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("b18aba7c-f135-4ada-8576-38b5a0acf974"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 15, 49, 817, DateTimeKind.Unspecified).AddTicks(7050), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Granite Car",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=471&blur",
                            Price = 914.45m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 10,
                            Stock = 4222,
                            AmountOfPerson = 1,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("d3fca6f7-ed4f-4b9b-ad99-142ca5e95dd9"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 23, 11, 6, 34, 8, DateTimeKind.Unspecified).AddTicks(2424), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Small Frozen Pizza",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=56&blur",
                            Price = 409.18m,
                            ProductTypeId = new Guid("3a1f0f73-2cd2-48a4-b343-d7df28b5387b"),
                            Rating = 6,
                            Stock = 3649,
                            AmountOfPerson = 1,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("b9145011-9f69-4fea-9ef4-71fb913fd8fc"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 24, 10, 11, 47, 544, DateTimeKind.Unspecified).AddTicks(3101), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Frozen Pants",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=295&blur",
                            Price = 117.45m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 10,
                            Stock = 2234,
                            AmountOfPerson = 1,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("fc4edcd6-7412-49be-8d96-296a4b399a8e"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 21, 16, 46, 0, 252, DateTimeKind.Unspecified).AddTicks(3705), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Rubber Soap",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=947&blur",
                            Price = 16.22m,
                            ProductTypeId = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84"),
                            Rating = 1,
                            Stock = 1264,
                            AmountOfPerson = 1,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("e0163b62-59d2-4fb5-92ee-8cefd8687b93"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 18, 11, 47, 5, 168, DateTimeKind.Unspecified).AddTicks(3889), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Fresh Shirt",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=520&blur",
                            Price = 608.07m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 0,
                            Stock = 3635,
                            AmountOfPerson = 2,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("18a4ea4e-0c2b-493a-a0cf-6f1ea30a61b6"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 15, 0, 31, 54, 978, DateTimeKind.Unspecified).AddTicks(9743), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Frozen Pants",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1041&blur",
                            Price = 53.51m,
                            ProductTypeId = new Guid("3a1f0f73-2cd2-48a4-b343-d7df28b5387b"),
                            Rating = 10,
                            Stock = 2036,
                            AmountOfPerson = 3,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("5e73023d-d64f-4fe7-ad5a-5088c43bf624"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 22, 23, 18, 50, 887, DateTimeKind.Unspecified).AddTicks(5207), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Concrete Keyboard",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1057&blur",
                            Price = 301.05m,
                            ProductTypeId = new Guid("54859554-ca78-4f20-ac6d-c23e43865384"),
                            Rating = 6,
                            Stock = 4433,
                            AmountOfPerson = 3,
                            KayakType = "Family"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeOne", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cedff71a-8449-4ff7-99d8-1823a1bfbe84")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeThree", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeThree");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a1f0f73-2cd2-48a4-b343-d7df28b5387b")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeTwo", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeTwo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54859554-ca78-4f20-ac6d-c23e43865384")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
