// <auto-generated />
using System;
using Dotnet6.GraphQL4.Store.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotnet6.GraphQL4.Store.Repositories.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("IntroduceAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d1a2300-b7a6-44e1-8422-a95ad74a8a1d"),
                            Comment = "Quis fugit quisquam quis et itaque velit. Error maxime consequatur recusandae. Ea aut modi et at. Occaecati unde illo consequatur. Quae facere omnis voluptatem numquam sequi laborum veritatis quo.\n\nDolorem et commodi voluptas temporibus repudiandae facilis temporibus sed. Quis esse consequatur. Non rerum qui. Ea perspiciatis eum quam culpa. Adipisci qui similique esse. Aspernatur nihil sit dignissimos eum aut suscipit in deleniti itaque.\n\nIure quia qui excepturi velit voluptatem. Possimus veniam eos harum. Cumque laudantium dolorem ipsam.",
                            ProductId = new Guid("8318e7f4-615f-4401-80f5-121522b7a279"),
                            Title = "Dicta et quo esse quisquam inventore."
                        },
                        new
                        {
                            Id = new Guid("1ea1edbc-958b-4ea2-b9ae-de606e7c573a"),
                            Comment = "Exercitationem totam autem vel laboriosam. Fuga at consequatur doloribus fugit. Sit qui voluptatem qui.\n\nVelit assumenda aut. Consequatur ut quos. Non architecto eaque blanditiis molestiae aspernatur adipisci non itaque qui. Aliquam ut doloremque ab excepturi consequatur qui. Eligendi accusantium rerum perferendis ipsa et perspiciatis ipsum. Totam sunt in ad.\n\nMollitia officia itaque non velit ut eum ratione quis. Omnis natus aspernatur molestiae qui. Modi dolores qui et et.",
                            ProductId = new Guid("02842c95-3473-4c9f-988b-2a6c4defb95c"),
                            Title = "Dignissimos voluptatem deserunt ad corporis est maiores sint enim magnam."
                        },
                        new
                        {
                            Id = new Guid("d7221f5b-0422-45e4-aec0-18452ed7801f"),
                            Comment = "Et sit ut numquam nam impedit non odit fugiat nihil. Eligendi architecto inventore eos aut qui dolor dolorem excepturi maiores. Dolor est qui sequi qui dolores.\n\nExplicabo non dolores voluptatum perferendis autem. Nihil harum repellat. Commodi consequatur ut doloribus nemo a veritatis vitae est aspernatur. Vitae consequatur culpa dolor omnis velit debitis temporibus.\n\nVoluptates unde quae deleniti molestiae. Voluptates in officia autem. Qui sit ut quos dolores aut odit. Explicabo id deleniti debitis a sapiente. Voluptatum sit et ea reprehenderit culpa. Autem ad odio.",
                            ProductId = new Guid("3c480dc4-b56c-4696-be22-94f2a8df8eca"),
                            Title = "Rem ducimus libero eum similique ut modi."
                        },
                        new
                        {
                            Id = new Guid("9787db1a-594c-451b-9d1c-c28bb8852cf4"),
                            Comment = "Incidunt quam consequatur blanditiis sequi temporibus occaecati nihil corrupti. Itaque consequuntur laboriosam eaque minima dolorum ipsum reprehenderit voluptates harum. Et sit et error qui sed molestiae. Eaque rem aut tenetur omnis.\n\nEt aut impedit maxime dolor ut qui dolorem adipisci in. Culpa reprehenderit hic sint enim amet. Et cum deleniti soluta quia aut quam. Eos debitis eius sit explicabo. Saepe eum dolor facilis quo eligendi et rerum facilis.\n\nDebitis mollitia laudantium nesciunt non est repellat saepe. Dignissimos quia fuga dolores tempora ut excepturi quo ipsam placeat. Aut nisi fugiat ut placeat in.",
                            ProductId = new Guid("820ad41e-0466-43ec-9b12-0ec52de0f86c"),
                            Title = "Eius maxime asperiores."
                        },
                        new
                        {
                            Id = new Guid("2ba73ef6-601c-44dd-aaeb-0ce084259e8d"),
                            Comment = "Nihil hic doloribus qui doloremque eveniet omnis ea. Laborum dolorum commodi dolor voluptas. Consectetur repudiandae possimus repellendus quod voluptas.\n\nQuo ducimus est voluptates eos eius ut pariatur quam. Eligendi architecto cum aperiam voluptates qui fuga. Dolores aut aperiam.\n\nAmet a doloremque officiis hic totam fugit rem. Laborum tenetur illo asperiores suscipit ipsam cumque. Aut temporibus fuga id aut illo eius dicta. Voluptatum dolores velit quae. Eos unde et reiciendis omnis quaerat dolores aliquam. Consequatur quia voluptate magni.",
                            ProductId = new Guid("79283d10-9770-4ae1-b0c8-346e3cb22656"),
                            Title = "Aspernatur nisi placeat consectetur sunt ratione."
                        },
                        new
                        {
                            Id = new Guid("e7ed569b-6ee5-4e38-922c-ce28bbfe0ea1"),
                            Comment = "Voluptas odit quam qui magnam fugit corporis iste. Qui rem aut dolore est. Corporis sed sit enim fugiat odit aut ea saepe numquam. Ipsa eligendi est illo. Aut officiis deleniti nam cumque quis qui provident. Et et sed dolorum atque aut.\n\nQuia voluptatem eligendi voluptatem quisquam ratione eius adipisci atque. Reiciendis laudantium corrupti qui quia atque. Delectus vel suscipit. Nulla sit autem laudantium molestiae laborum aut nam molestias error.\n\nRerum aut reprehenderit inventore placeat dolor atque consectetur perspiciatis voluptate. Harum voluptatem et perspiciatis eveniet dolor aut. Est et iste est magni architecto est iste tempore et. Nisi et sit possimus vel velit dolorum eius atque quis.",
                            ProductId = new Guid("0210e32a-6157-4763-87af-c3ae5cde3940"),
                            Title = "Corporis veritatis quae odit voluptas fugiat temporibus voluptatem suscipit unde."
                        },
                        new
                        {
                            Id = new Guid("39c148c1-0d4e-4ded-ba34-32b374c8f18e"),
                            Comment = "Error unde excepturi totam recusandae. Adipisci aut earum amet in aut quo sunt sit. Voluptates reprehenderit laudantium mollitia corrupti.\n\nNon accusamus dicta ipsam ratione commodi consequuntur quo. Sed qui fugit ut. Sequi reprehenderit quibusdam dolorum.\n\nA et tempora. Ea aspernatur reiciendis ut voluptatem quod aperiam tempora aperiam magnam. Consequatur eaque mollitia est ut. Expedita magnam qui excepturi quia velit.",
                            ProductId = new Guid("00d56434-f8e1-4cc6-a246-3b60c2e4bd7f"),
                            Title = "Et est ut neque qui vero ullam et voluptas."
                        },
                        new
                        {
                            Id = new Guid("dd73a0e7-bd2c-41cc-b582-b981d1891d83"),
                            Comment = "Quos aliquam totam illo fugiat sed iusto. Minus occaecati saepe iusto aspernatur aut. Alias enim ea magni quis molestias voluptatum velit.\n\nDebitis et sunt similique quam dignissimos. Pariatur impedit esse iusto doloribus ipsa rerum nisi. Cumque debitis voluptatem repudiandae. Nisi velit consectetur sint quaerat sequi dicta minus. Aut quos non cum accusamus ut maiores culpa. Explicabo velit sit at voluptas.\n\nEos consequatur corrupti labore maxime accusantium dolorum nesciunt quaerat ut. Et iusto necessitatibus facere ex animi nemo. Eos sequi sed aperiam aut omnis. Facilis exercitationem aspernatur alias voluptas fuga. Ratione eaque sit sed ab.",
                            ProductId = new Guid("81e0bf83-a3f5-4a38-b982-5e0c84f79e6b"),
                            Title = "Ipsum et alias dolorem nihil enim."
                        },
                        new
                        {
                            Id = new Guid("088ca74b-1dd9-41e0-876c-3265e695b919"),
                            Comment = "Rerum eveniet laudantium autem sint. Consequatur exercitationem a debitis nam iste eius laboriosam autem deleniti. Aliquam porro atque nihil qui nesciunt porro nihil. Quae dolorem voluptas eos perspiciatis labore quae ut corrupti. Eligendi officia minus cum. Ducimus harum fugit nisi hic cumque.\n\nNon eum et quis voluptate tenetur ex aut quia. Blanditiis natus omnis molestiae iure officia temporibus alias. Aut id reprehenderit aut iure non.\n\nQuae id dolorem eligendi veniam repudiandae non reiciendis aliquam. Non quis magnam. Optio dolorem cumque aut reprehenderit.",
                            ProductId = new Guid("115747c4-7bac-45c3-b916-b2b0a068fa4b"),
                            Title = "Aliquam quidem numquam placeat."
                        },
                        new
                        {
                            Id = new Guid("3543d2fb-a52c-4820-af95-e00416e2d881"),
                            Comment = "Occaecati libero dolorum esse voluptatem atque reiciendis non blanditiis qui. Repellat nostrum sint aut rerum unde ratione molestiae pariatur iusto. Velit est perspiciatis ducimus culpa earum aspernatur sed. Minus illum sint voluptate id est velit sed velit in.\n\nCupiditate sunt ut officia rem. Et aut dolorem voluptas quisquam possimus rem qui explicabo. Doloremque temporibus tenetur aliquid omnis voluptatem quos.\n\nDebitis rem modi expedita error. Sunt ut et et facere a error. Est consequatur fuga qui qui. Est libero ut et sapiente maxime et reiciendis inventore. Ullam in et cupiditate.",
                            ProductId = new Guid("53839868-fc56-4157-9aa5-f85d9825efa3"),
                            Title = "Rerum accusamus ea rerum minus repellendus tempore maxime velit adipisci."
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Backpacks.Backpack", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BackpackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Backpack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84aea957-9f2e-41f0-b327-c24df0ccc8ec"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 14, 0, 5, 54, 442, DateTimeKind.Unspecified).AddTicks(7619), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Metal Shoes",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=81&blur",
                            Price = 29.97m,
                            ProductTypeId = new Guid("5fc2dfdd-c0c6-4e88-91ef-5ac29a8cc0f2"),
                            Rating = 7,
                            Stock = 4866,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("df7e87f2-a25e-4e9e-8ee6-80a6a874f1c7"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 17, 20, 57, 13, 234, DateTimeKind.Unspecified).AddTicks(2308), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Cotton Cheese",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=345&blur",
                            Price = 434.09m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 10,
                            Stock = 2552,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("7d24453c-a245-4340-bac9-f34c686dd005"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 9, 1, 29, 5, 694, DateTimeKind.Unspecified).AddTicks(5566), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Generic Steel Table",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=336&blur",
                            Price = 223.18m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 1,
                            Stock = 2744,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("696907a3-ab0d-432d-bf66-c57f89c3c120"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 7, 3, 35, 8, 251, DateTimeKind.Unspecified).AddTicks(829), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handcrafted Cotton Chips",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=271&blur",
                            Price = 533.79m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 4,
                            Stock = 1541,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("05ba3c27-de61-4e49-9590-4c67ea583612"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 12, 2, 22, 47, 715, DateTimeKind.Unspecified).AddTicks(7718), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Metal Soap",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=435&blur",
                            Price = 39.37m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 2,
                            Stock = 4834,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("a80e2df9-1516-445a-9885-7f23728fcd36"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 5, 8, 0, 2, 37, DateTimeKind.Unspecified).AddTicks(8846), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Cotton Ball",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=895&blur",
                            Price = 865.06m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 3,
                            Stock = 4159,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("8a3f8101-a72f-42b0-9d8d-c2f805f55ca4"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 28, 16, 13, 50, 876, DateTimeKind.Unspecified).AddTicks(7074), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Rubber Computer",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=557&blur",
                            Price = 988.62m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 6,
                            Stock = 970,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("72ec876e-8f81-43b6-99c4-0caf84cc5c52"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 17, 3, 54, 43, 339, DateTimeKind.Unspecified).AddTicks(7693), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Small Concrete Pants",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=730&blur",
                            Price = 804.40m,
                            ProductTypeId = new Guid("5fc2dfdd-c0c6-4e88-91ef-5ac29a8cc0f2"),
                            Rating = 10,
                            Stock = 690,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("686b866e-03da-4946-88ff-951d36d7d052"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 6, 7, 50, 17, 999, DateTimeKind.Unspecified).AddTicks(3024), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Rubber Salad",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=810&blur",
                            Price = 989.35m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 7,
                            Stock = 83,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("c990c789-cc3c-4c42-b884-ee7d8d1c44d6"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 24, 7, 45, 39, 230, DateTimeKind.Unspecified).AddTicks(7884), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Concrete Ball",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=599&blur",
                            Price = 521.32m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 3,
                            Stock = 1059,
                            BackpackType = "Cycling"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Boots.Boot", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BootType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Boot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26b72de2-fcc2-48cc-993c-33dccabf1737"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 21, 20, 29, 23, 858, DateTimeKind.Unspecified).AddTicks(213), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Granite Cheese",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=989&blur",
                            Price = 693.80m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 5,
                            Stock = 4780,
                            BootType = "Chelsea",
                            Size = 30
                        },
                        new
                        {
                            Id = new Guid("bf2cf5eb-63ad-48af-9a50-cf8cb7e36383"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 20, 22, 25, 38, 413, DateTimeKind.Unspecified).AddTicks(205), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Steel Mouse",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1014&blur",
                            Price = 6.68m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 1,
                            Stock = 2790,
                            BootType = "Football",
                            Size = 23
                        },
                        new
                        {
                            Id = new Guid("2eabc83f-d9eb-4ca3-8cb9-7e119b199edd"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 31, 8, 18, 43, 126, DateTimeKind.Unspecified).AddTicks(2764), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Soft Car",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=935&blur",
                            Price = 918.05m,
                            ProductTypeId = new Guid("5fc2dfdd-c0c6-4e88-91ef-5ac29a8cc0f2"),
                            Rating = 9,
                            Stock = 4003,
                            BootType = "Harness",
                            Size = 25
                        },
                        new
                        {
                            Id = new Guid("33ac1474-f1c6-44ac-8209-73f13e7e0317"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 8, 17, 33, 27, 535, DateTimeKind.Unspecified).AddTicks(1708), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Steel Ball",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=378&blur",
                            Price = 52.62m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 0,
                            Stock = 3289,
                            BootType = "Cowboy",
                            Size = 30
                        },
                        new
                        {
                            Id = new Guid("35163381-b9f8-4498-a40a-0b14b9db4d61"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 9, 22, 44, 36, 356, DateTimeKind.Unspecified).AddTicks(2481), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Metal Chicken",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=50&blur",
                            Price = 836.59m,
                            ProductTypeId = new Guid("5fc2dfdd-c0c6-4e88-91ef-5ac29a8cc0f2"),
                            Rating = 1,
                            Stock = 3556,
                            BootType = "Engineer",
                            Size = 24
                        },
                        new
                        {
                            Id = new Guid("f77c6e93-56c9-46b7-a96a-f46db47a6797"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 17, 1, 40, 39, 213, DateTimeKind.Unspecified).AddTicks(9360), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Concrete Salad",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=777&blur",
                            Price = 863.72m,
                            ProductTypeId = new Guid("5fc2dfdd-c0c6-4e88-91ef-5ac29a8cc0f2"),
                            Rating = 2,
                            Stock = 1662,
                            BootType = "Harness",
                            Size = 21
                        },
                        new
                        {
                            Id = new Guid("6efe8f37-ed6c-420f-a5eb-faa436132b4e"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 6, 1, 54, 36, 932, DateTimeKind.Unspecified).AddTicks(3846), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Rubber Shoes",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=322&blur",
                            Price = 721.04m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 6,
                            Stock = 454,
                            BootType = "Football",
                            Size = 24
                        },
                        new
                        {
                            Id = new Guid("7fa97045-2859-4bbc-b05a-a1345cc0a227"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 6, 9, 43, 0, 572, DateTimeKind.Unspecified).AddTicks(3435), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handcrafted Soft Pants",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=789&blur",
                            Price = 629.00m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 7,
                            Stock = 2383,
                            BootType = "Cowboy",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("fa7d2db5-b255-492e-9734-fc0c9df58a65"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 19, 18, 39, 12, 256, DateTimeKind.Unspecified).AddTicks(1089), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handmade Granite Shirt",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=122&blur",
                            Price = 926.74m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 7,
                            Stock = 3442,
                            BootType = "Harness",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("d3b257c6-93e9-4f55-adaf-9c46335295b5"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 1, 18, 37, 26, 741, DateTimeKind.Unspecified).AddTicks(1673), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Soft Computer",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=816&blur",
                            Price = 605.77m,
                            ProductTypeId = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45"),
                            Rating = 2,
                            Stock = 2090,
                            BootType = "Cowboy",
                            Size = 22
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Kayaks.Kayak", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<int>("AmountOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("KayakType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kayak");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8318e7f4-615f-4401-80f5-121522b7a279"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 4, 25, 19, 14, 6, 784, DateTimeKind.Unspecified).AddTicks(5801), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Steel Gloves",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=489&blur",
                            Price = 829.98m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 0,
                            Stock = 859,
                            AmountOfPerson = 3,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("02842c95-3473-4c9f-988b-2a6c4defb95c"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 21, 15, 29, 13, 800, DateTimeKind.Unspecified).AddTicks(7763), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Concrete Shirt",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=125&blur",
                            Price = 14.84m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 1,
                            Stock = 3379,
                            AmountOfPerson = 2,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("3c480dc4-b56c-4696-be22-94f2a8df8eca"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 5, 14, 35, 35, 480, DateTimeKind.Unspecified).AddTicks(495), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Concrete Mouse",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=105&blur",
                            Price = 51.85m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 8,
                            Stock = 1621,
                            AmountOfPerson = 2,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("820ad41e-0466-43ec-9b12-0ec52de0f86c"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 21, 20, 20, 15, 775, DateTimeKind.Unspecified).AddTicks(297), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Plastic Car",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=427&blur",
                            Price = 218.74m,
                            ProductTypeId = new Guid("5fc2dfdd-c0c6-4e88-91ef-5ac29a8cc0f2"),
                            Rating = 0,
                            Stock = 758,
                            AmountOfPerson = 3,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("79283d10-9770-4ae1-b0c8-346e3cb22656"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 18, 5, 35, 26, 367, DateTimeKind.Unspecified).AddTicks(7695), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Wooden Towels",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=481&blur",
                            Price = 57.33m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 4,
                            Stock = 4859,
                            AmountOfPerson = 1,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("0210e32a-6157-4763-87af-c3ae5cde3940"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 26, 21, 22, 1, 869, DateTimeKind.Unspecified).AddTicks(3340), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Generic Steel Cheese",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=337&blur",
                            Price = 245.28m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 1,
                            Stock = 2161,
                            AmountOfPerson = 1,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("00d56434-f8e1-4cc6-a246-3b60c2e4bd7f"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 8, 3, 20, 30, 211, DateTimeKind.Unspecified).AddTicks(722), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Fresh Keyboard",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=56&blur",
                            Price = 695.82m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 6,
                            Stock = 292,
                            AmountOfPerson = 3,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("81e0bf83-a3f5-4a38-b982-5e0c84f79e6b"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 14, 3, 23, 15, 59, DateTimeKind.Unspecified).AddTicks(9801), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Granite Shirt",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=868&blur",
                            Price = 631.30m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 10,
                            Stock = 1795,
                            AmountOfPerson = 1,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("115747c4-7bac-45c3-b916-b2b0a068fa4b"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 6, 9, 43, 56, 943, DateTimeKind.Unspecified).AddTicks(3255), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Generic Wooden Shirt",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=230&blur",
                            Price = 152.87m,
                            ProductTypeId = new Guid("5fc2dfdd-c0c6-4e88-91ef-5ac29a8cc0f2"),
                            Rating = 2,
                            Stock = 2257,
                            AmountOfPerson = 3,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("53839868-fc56-4157-9aa5-f85d9825efa3"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 11, 13, 9, 54, 52, DateTimeKind.Unspecified).AddTicks(3738), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Frozen Gloves",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=772&blur",
                            Price = 160.95m,
                            ProductTypeId = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2"),
                            Rating = 0,
                            Stock = 2114,
                            AmountOfPerson = 1,
                            KayakType = "Camping"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeOne", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fc2dfdd-c0c6-4e88-91ef-5ac29a8cc0f2")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeThree", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeThree");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6625126-6b35-424b-a8f1-3ecf64a56c45")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeTwo", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeTwo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12c1515d-6aef-4191-b69e-89bd48238eb2")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
