// <auto-generated />
using System;
using Dotnet6.GraphQL4.Store.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Dotnet6.GraphQL4.Store.Repositories.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("IntroduceAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9dc3f7ed-69dd-439c-9cf7-0d5cc33d3bef"),
                            Comment = "Dolor possimus nobis iste laboriosam cupiditate et velit qui est. Alias consequatur velit ducimus. Quas expedita quia qui. Nemo quidem nihil. Debitis id eveniet autem.\n\nQuaerat quidem veniam. Velit quia dolor nostrum vel harum corporis. Fuga quis ut impedit unde molestiae voluptatibus a voluptatem odio. Et rem sed reiciendis ea praesentium temporibus animi dolorem quia. Molestiae consequatur cupiditate saepe aperiam fugit voluptas consequatur. Explicabo temporibus nisi perferendis suscipit exercitationem ipsum amet rem.\n\nEst illum quo. Quae nostrum ratione qui eum deserunt. Deleniti temporibus et. Sed sit expedita reprehenderit accusamus harum.",
                            ProductId = new Guid("7bbbd348-8004-4b1b-891e-801f506569f8"),
                            Title = "Est dolorem beatae magni odit facilis veritatis nostrum animi magni."
                        },
                        new
                        {
                            Id = new Guid("fe064c58-5f3d-4898-a0e5-9647744740d8"),
                            Comment = "Accusantium odit et odit. Quod ut molestias sed sed veritatis enim omnis odit. Omnis doloribus provident beatae occaecati vel id ipsum necessitatibus laboriosam. Amet et possimus ut asperiores ut ipsa et aut laboriosam.\n\nConsequatur et ut. Esse ducimus voluptas. Culpa repellat facere ullam ullam et illo repudiandae repellendus. Itaque voluptas assumenda recusandae iste. Placeat repellat quia nesciunt ut molestiae. Omnis aut repudiandae quisquam.\n\nAliquam voluptatem est quia in sit amet. Blanditiis labore molestiae pariatur magni voluptas officia in. Nemo debitis aspernatur. Autem quam labore est dolores expedita.",
                            ProductId = new Guid("c5115844-c058-4c9b-870f-345ed623f9eb"),
                            Title = "Sed quam eum nisi et exercitationem provident ut numquam."
                        },
                        new
                        {
                            Id = new Guid("234f9983-d776-431e-aee1-acb47ae02fea"),
                            Comment = "Animi consequatur quisquam nostrum. Minima enim eos vitae rerum voluptatem omnis est nulla. Amet aut ut atque sint. Cum esse perspiciatis. At culpa eius.\n\nEt amet rem fugit ad. Quo vitae distinctio a ullam ea sunt magni. Expedita omnis et. Aut et et qui magni. Molestiae tenetur quia. Ut optio explicabo corporis est.\n\nQuis dolores similique animi rem quibusdam et non numquam quisquam. Veniam dolores vel. Vitae sint est.",
                            ProductId = new Guid("d5498321-41f6-484c-8228-dc325a357340"),
                            Title = "Omnis blanditiis nisi repellat aliquid omnis sed eum."
                        },
                        new
                        {
                            Id = new Guid("1211a217-b147-4f87-9eef-c274df60f2d2"),
                            Comment = "Sed illo et aut vitae. Minima recusandae cumque quidem at. Sed repudiandae qui dolorem libero soluta debitis dolorem et. Culpa fugit rem excepturi. Et numquam dolorem itaque ut atque ut perferendis nam ullam. Velit aut et voluptatem.\n\nAut est aliquam. Animi non odit vero hic recusandae. Accusantium voluptatum nobis rerum sunt nihil omnis porro.\n\nAut laboriosam itaque ut qui cupiditate dolores ut. Accusantium laudantium sapiente corrupti nemo maxime quaerat excepturi eveniet. Porro beatae sit omnis fuga maiores consectetur laborum. Voluptas qui voluptatem iusto suscipit reprehenderit molestiae. Ipsam provident accusamus alias est officia. Voluptates dolor et.",
                            ProductId = new Guid("7db9e906-bc20-44c8-8421-204033e81e8d"),
                            Title = "Vel eveniet ipsam repudiandae aut accusantium neque dolorum eos repellendus."
                        },
                        new
                        {
                            Id = new Guid("71854736-db2b-4142-b779-f3109495496b"),
                            Comment = "Ut voluptates delectus molestiae veniam alias doloremque et aspernatur eum. Earum reiciendis accusantium nobis odit. Recusandae facilis dignissimos et sed ut. Cupiditate tempore qui voluptate quia est veritatis animi.\n\nSit explicabo rerum neque aut et ratione. Necessitatibus asperiores ut autem recusandae at. Illo magni non eos accusamus.\n\nCum suscipit ut est eos. Blanditiis voluptas quia facere itaque commodi optio. Laudantium voluptas magni quod ullam atque ipsam. Sunt voluptatem id nostrum. Quia rerum dolores. Dolores dolorum asperiores quam nemo voluptatem.",
                            ProductId = new Guid("f86e74c6-1c6a-4301-938a-cf62b1779ef7"),
                            Title = "Quae cupiditate voluptatibus error."
                        },
                        new
                        {
                            Id = new Guid("84ebe1d8-134b-4cf8-947c-4a0c7cc2b2a2"),
                            Comment = "Iusto sunt sequi placeat officia aut quibusdam in sunt. Voluptatem iusto et placeat officiis similique iste. Nobis consectetur nostrum et quod. Quia nesciunt veritatis itaque eligendi est quas facere. Corporis porro dolorem dolores voluptatem provident quo.\n\nError aut aut. Et sint quia voluptatum ut facilis debitis atque dolores harum. Qui in et quod eos impedit quibusdam consequatur enim. Itaque aperiam impedit iusto ut et pariatur at incidunt.\n\nQui consectetur sunt unde et numquam aut vero. Vitae consequatur vitae suscipit soluta maxime aut explicabo rem. Voluptas aut nihil fugit magni.",
                            ProductId = new Guid("6c147702-df13-488a-8623-0a12394d4fea"),
                            Title = "Et ipsa minus nulla doloremque et."
                        },
                        new
                        {
                            Id = new Guid("135411cb-4cec-4164-9185-d336bf137f41"),
                            Comment = "Velit est eum laboriosam adipisci dolore. Asperiores voluptatem qui repellendus magni hic. Facere quos optio facere vel. Rem provident voluptatem beatae sapiente et alias quia quasi aut.\n\nPerspiciatis est eos tenetur ea voluptas. Tempora eos est hic nemo sit repellat provident et nostrum. Voluptatem minima dolore eum. Libero nihil nemo vel consequuntur dolore ipsam et eos iste. Qui voluptatem ut quibusdam magni. Pariatur sequi voluptatem cumque culpa porro maxime sapiente sed possimus.\n\nEos error non neque voluptas rem magnam illo eum. Voluptatibus perspiciatis pariatur vel facere alias esse ut aut. Odit eius molestiae explicabo ea eius. Maiores natus esse. Corrupti et sunt minima doloribus sed quam. Omnis perspiciatis beatae unde beatae ipsum.",
                            ProductId = new Guid("b03c8456-d4c8-4c6a-aeda-3cb4c4b7acf4"),
                            Title = "At voluptas sapiente maxime unde ut."
                        },
                        new
                        {
                            Id = new Guid("13994935-5a71-48f1-a51b-5b853c42b8f4"),
                            Comment = "Est facilis eos fugit et perspiciatis. Ut dolores ut dolor dolores aut. Provident omnis aut asperiores assumenda dolore hic doloremque libero. Et aut consequatur voluptatem voluptatem. Accusamus voluptas quod eaque consequatur quidem pariatur alias et.\n\nMinima culpa culpa eveniet cum consequatur. Ut sed eos. Et et dignissimos eligendi aut temporibus adipisci. Quia veritatis et soluta aspernatur at facere quasi iure eveniet. Aut autem illum accusamus libero ducimus sunt qui et sint. Dicta qui tenetur ipsam eum.\n\nCum distinctio inventore consequatur optio omnis ipsam. Ut deleniti ipsa. Ullam impedit suscipit nostrum voluptatibus dolor soluta et omnis et.",
                            ProductId = new Guid("1a209ada-113f-48c6-a446-7f6ed7d74177"),
                            Title = "Laboriosam hic ea ut aut quam est repellendus accusantium excepturi."
                        },
                        new
                        {
                            Id = new Guid("0be6c303-8fa4-41a0-ac75-f71234e1ecb6"),
                            Comment = "Ut at quasi soluta eaque iste harum unde. Voluptate quia eius similique facere provident aut. Ratione laborum qui iusto. Quisquam vero nostrum officiis laboriosam et quia optio sit.\n\nRepellat aspernatur iusto voluptates et facilis architecto ratione eligendi. Recusandae et amet suscipit modi. Facere est aut eveniet expedita ad blanditiis magni numquam iure. Numquam perferendis quis repudiandae.\n\nQui similique et explicabo veritatis quidem et ut tempore quod. Temporibus tempora odit ut fugit minus nihil. Eos excepturi dolorem. Rerum nemo optio fugit deleniti vero dolores quia.",
                            ProductId = new Guid("6c9a1032-b422-4cd7-9527-7b558d9cc2bc"),
                            Title = "Perspiciatis porro autem voluptas sunt."
                        },
                        new
                        {
                            Id = new Guid("73eddb2b-cf7b-4c8f-bbc2-a01ecd1ef9c0"),
                            Comment = "Aut vel ex voluptatibus sed tenetur nisi maiores. Fuga aspernatur minima rerum accusamus. In tempora pariatur aut temporibus. Cupiditate voluptatem nobis ut esse. Et molestias enim est. Itaque minus eaque possimus sequi amet amet.\n\nImpedit eum at possimus at autem quos nostrum voluptatem similique. Natus alias quia atque ex tempore odio sed consequatur aspernatur. Ut at iste nisi non eum. Et eaque distinctio voluptatem dolorem expedita. Dolorem molestiae est ipsa et hic consectetur maxime.\n\nRecusandae velit omnis ea atque placeat quasi aut eos ut. Alias sed molestias neque distinctio et beatae non quaerat. Dolor nam temporibus consectetur. Placeat beatae sequi voluptatem quis tempora repellat sunt. Et minima sunt omnis quis deserunt. Delectus quam fugiat dolorem quisquam dolor.",
                            ProductId = new Guid("8f7cfbdd-3413-44ae-b987-052fd9f3bfdd"),
                            Title = "Asperiores voluptatem fugit numquam mollitia quod possimus maxime voluptas non."
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Backpacks.Backpack", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BackpackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Backpack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c78129c-0cdf-4efc-b9dd-26daa427cec7"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 23, 20, 21, 12, 456, DateTimeKind.Unspecified).AddTicks(3393), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Soft Towels",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=179&blur",
                            Price = 101.81m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 7,
                            Stock = 581,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("fac1b0aa-ba75-434a-beb3-cdf3322678ea"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 10, 7, 24, 59, 922, DateTimeKind.Unspecified).AddTicks(4141), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Steel Computer",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=603&blur",
                            Price = 410.94m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 3,
                            Stock = 4523,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("2d26d129-0e07-4222-8924-9ae6d6826b00"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 30, 12, 19, 15, 132, DateTimeKind.Unspecified).AddTicks(8023), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Steel Fish",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1010&blur",
                            Price = 944.09m,
                            ProductTypeId = new Guid("8be5fcac-91a2-40e8-b23e-e2d9c24b0bc8"),
                            Rating = 0,
                            Stock = 1195,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("a8446d31-ce66-4f3f-a283-5de0a6d1284c"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 3, 10, 49, 52, 298, DateTimeKind.Unspecified).AddTicks(2036), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Cotton Ball",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=854&blur",
                            Price = 811.98m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 7,
                            Stock = 2982,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("ef478e2f-e8f5-4b5b-8cb8-0be62066a2d1"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 22, 22, 5, 19, 269, DateTimeKind.Unspecified).AddTicks(4749), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Soft Tuna",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=706&blur",
                            Price = 209.82m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 9,
                            Stock = 444,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("5afd934e-fa56-4ed1-a466-77d0ddc4a8c6"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 27, 16, 44, 37, 566, DateTimeKind.Unspecified).AddTicks(9590), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Rubber Bacon",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=872&blur",
                            Price = 489.99m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 8,
                            Stock = 1954,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("cb342ad0-ce8d-418b-8eae-b05cd32ddff9"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 18, 10, 50, 29, 635, DateTimeKind.Unspecified).AddTicks(4546), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Metal Shoes",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=283&blur",
                            Price = 701.24m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 7,
                            Stock = 2548,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("e38e6ad6-4f73-4973-8f30-5773492b2a72"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 16, 17, 15, 9, 619, DateTimeKind.Unspecified).AddTicks(7982), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Rubber Chicken",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=63&blur",
                            Price = 285.69m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 7,
                            Stock = 3087,
                            BackpackType = "DayPack"
                        },
                        new
                        {
                            Id = new Guid("a4779665-8130-4ce5-8b56-768830132007"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 5, 20, 25, 2, 795, DateTimeKind.Unspecified).AddTicks(2268), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Wooden Shirt",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=758&blur",
                            Price = 770.78m,
                            ProductTypeId = new Guid("8be5fcac-91a2-40e8-b23e-e2d9c24b0bc8"),
                            Rating = 4,
                            Stock = 4912,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("4909b9a6-6dfc-469c-8eac-cc1ea27968ef"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 26, 3, 7, 49, 705, DateTimeKind.Unspecified).AddTicks(2788), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Wooden Hat",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=114&blur",
                            Price = 349.12m,
                            ProductTypeId = new Guid("8be5fcac-91a2-40e8-b23e-e2d9c24b0bc8"),
                            Rating = 9,
                            Stock = 2595,
                            BackpackType = "Hiking"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Boots.Boot", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BootType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Boot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3746c74-063f-4f71-816e-c717de1c464d"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 23, 11, 1, 21, 543, DateTimeKind.Unspecified).AddTicks(2186), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Steel Gloves",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=345&blur",
                            Price = 953.12m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 10,
                            Stock = 3755,
                            BootType = "Drysuit",
                            Size = 29
                        },
                        new
                        {
                            Id = new Guid("f256d6e1-720d-4add-b9ae-11dd81c41358"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 29, 6, 56, 48, 421, DateTimeKind.Unspecified).AddTicks(391), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Frozen Table",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=649&blur",
                            Price = 125.63m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 4,
                            Stock = 2372,
                            BootType = "Engineer",
                            Size = 25
                        },
                        new
                        {
                            Id = new Guid("eddd683d-5311-41d0-b361-8f10bf3e5d1d"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 2, 3, 48, 40, 851, DateTimeKind.Unspecified).AddTicks(2434), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Concrete Bacon",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=751&blur",
                            Price = 42.64m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 3,
                            Stock = 4510,
                            BootType = "Chelsea",
                            Size = 28
                        },
                        new
                        {
                            Id = new Guid("10d9b9ec-4dfc-4950-a305-bb1c126bac07"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 3, 23, 36, 58, 77, DateTimeKind.Unspecified).AddTicks(9190), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Concrete Pants",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1040&blur",
                            Price = 380.71m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 2,
                            Stock = 326,
                            BootType = "Football",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("8e54b1ba-052a-49a6-9042-81e19ec9c37c"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 11, 21, 26, 23, 921, DateTimeKind.Unspecified).AddTicks(7406), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Small Metal Shoes",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=158&blur",
                            Price = 199.08m,
                            ProductTypeId = new Guid("8be5fcac-91a2-40e8-b23e-e2d9c24b0bc8"),
                            Rating = 1,
                            Stock = 2105,
                            BootType = "Engineer",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("8057a79c-34ac-4699-b2ad-97c8fdda9d5e"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 23, 3, 37, 26, 809, DateTimeKind.Unspecified).AddTicks(2142), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Fresh Bacon",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=306&blur",
                            Price = 500.32m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 3,
                            Stock = 2359,
                            BootType = "Chelsea",
                            Size = 30
                        },
                        new
                        {
                            Id = new Guid("b1347aef-5a1a-4c91-99ed-b299d93ec59f"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 19, 2, 8, 36, 805, DateTimeKind.Unspecified).AddTicks(3368), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Plastic Salad",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=675&blur",
                            Price = 767.91m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 4,
                            Stock = 4849,
                            BootType = "Harness",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("cc271931-7c04-45ba-b363-c32c50871bf3"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 12, 17, 37, 3, 457, DateTimeKind.Unspecified).AddTicks(5076), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handcrafted Granite Cheese",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=897&blur",
                            Price = 810.90m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 5,
                            Stock = 4709,
                            BootType = "Drysuit",
                            Size = 23
                        },
                        new
                        {
                            Id = new Guid("f6381f0e-6954-4581-88e1-cb033794cb04"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 27, 13, 35, 26, 566, DateTimeKind.Unspecified).AddTicks(2722), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Soft Cheese",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=337&blur",
                            Price = 530.99m,
                            ProductTypeId = new Guid("8be5fcac-91a2-40e8-b23e-e2d9c24b0bc8"),
                            Rating = 5,
                            Stock = 2692,
                            BootType = "Football",
                            Size = 25
                        },
                        new
                        {
                            Id = new Guid("d8cce645-be14-42c2-96b2-7720b9d1e433"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 17, 19, 10, 31, 666, DateTimeKind.Unspecified).AddTicks(895), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Fresh Towels",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=915&blur",
                            Price = 264.98m,
                            ProductTypeId = new Guid("8be5fcac-91a2-40e8-b23e-e2d9c24b0bc8"),
                            Rating = 3,
                            Stock = 3190,
                            BootType = "Harness",
                            Size = 29
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Kayaks.Kayak", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<int>("AmountOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("KayakType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kayak");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bbbd348-8004-4b1b-891e-801f506569f8"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 24, 17, 42, 57, 419, DateTimeKind.Unspecified).AddTicks(1712), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Awesome Granite Pants",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=866&blur",
                            Price = 56.24m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 8,
                            Stock = 1039,
                            AmountOfPerson = 2,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("c5115844-c058-4c9b-870f-345ed623f9eb"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 4, 7, 5, 37, 12, 266, DateTimeKind.Unspecified).AddTicks(3138), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Unbranded Steel Ball",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=136&blur",
                            Price = 819.35m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 7,
                            Stock = 2553,
                            AmountOfPerson = 3,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("d5498321-41f6-484c-8228-dc325a357340"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 26, 0, 23, 4, 722, DateTimeKind.Unspecified).AddTicks(9226), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Concrete Tuna",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=600&blur",
                            Price = 134.06m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 4,
                            Stock = 1990,
                            AmountOfPerson = 1,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("7db9e906-bc20-44c8-8421-204033e81e8d"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 9, 17, 9, 32, 38, DateTimeKind.Unspecified).AddTicks(1829), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handcrafted Frozen Ball",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=218&blur",
                            Price = 367.81m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 8,
                            Stock = 2851,
                            AmountOfPerson = 3,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("f86e74c6-1c6a-4301-938a-cf62b1779ef7"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 25, 23, 16, 36, 887, DateTimeKind.Unspecified).AddTicks(2759), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Cotton Ball",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=702&blur",
                            Price = 518.11m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 10,
                            Stock = 4957,
                            AmountOfPerson = 3,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("6c147702-df13-488a-8623-0a12394d4fea"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 2, 14, 49, 7, 275, DateTimeKind.Unspecified).AddTicks(8430), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Ergonomic Soft Gloves",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=679&blur",
                            Price = 148.96m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 9,
                            Stock = 1487,
                            AmountOfPerson = 1,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("b03c8456-d4c8-4c6a-aeda-3cb4c4b7acf4"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 10, 1, 33, 58, 878, DateTimeKind.Unspecified).AddTicks(4324), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Granite Chicken",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=45&blur",
                            Price = 832.62m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 2,
                            Stock = 3374,
                            AmountOfPerson = 1,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("1a209ada-113f-48c6-a446-7f6ed7d74177"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 3, 25, 2, 32, 42, 421, DateTimeKind.Unspecified).AddTicks(252), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Rubber Computer",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1033&blur",
                            Price = 407.97m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 9,
                            Stock = 4730,
                            AmountOfPerson = 3,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("6c9a1032-b422-4cd7-9527-7b558d9cc2bc"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 8, 2, 20, 57, 647, DateTimeKind.Unspecified).AddTicks(1842), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Rubber Mouse",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1084&blur",
                            Price = 87.32m,
                            ProductTypeId = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15"),
                            Rating = 8,
                            Stock = 4842,
                            AmountOfPerson = 2,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("8f7cfbdd-3413-44ae-b987-052fd9f3bfdd"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 26, 8, 51, 18, 511, DateTimeKind.Unspecified).AddTicks(2321), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Metal Hat",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=218&blur",
                            Price = 95.87m,
                            ProductTypeId = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006"),
                            Rating = 0,
                            Stock = 2584,
                            AmountOfPerson = 3,
                            KayakType = "Family"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeOne", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fcf9d0df-a663-4687-bdae-4c2b2db3ac15")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeThree", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeThree");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0156fb5-a199-4e0a-8202-00492d9ef006")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeTwo", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeTwo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8be5fcac-91a2-40e8-b23e-e2d9c24b0bc8")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
