// <auto-generated />
using System;
using Dotnet6.GraphQL4.Store.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotnet6.GraphQL4.Store.Repositories.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTimeOffset>("IntroduceAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c41b1eb3-ddfc-403b-a3ce-e74939d45864"),
                            Comment = "Cumque impedit et labore velit. Iure et in aut consequatur. Veniam qui aut est sapiente.\n\nEt ducimus saepe possimus. Consectetur delectus eveniet deserunt et nulla in dignissimos magnam. Repellendus officia minus.\n\nOmnis aspernatur voluptatum. Minus natus culpa. At est omnis.",
                            ProductId = new Guid("e852fab1-4dc0-46ec-a9db-184e4b8d96a6"),
                            Title = "Sunt consequatur atque eius provident quam nesciunt."
                        },
                        new
                        {
                            Id = new Guid("28bea6fe-9e8b-4b19-aaa3-e96e12a5c954"),
                            Comment = "Dolor quibusdam atque esse officiis. Aperiam quaerat sit vel nostrum. Optio aut cupiditate. Debitis perspiciatis qui minima ut dolor. Sint dolorem labore maxime sequi quia. Qui dolor qui libero dignissimos iusto eos qui totam esse.\n\nFugiat ullam atque et enim autem. Omnis reiciendis sint debitis sed quis autem et vitae qui. Itaque quis ut modi assumenda. Itaque eligendi consequatur voluptatem occaecati atque voluptatem quod consequatur. Adipisci voluptas est.\n\nEum pariatur consequatur aliquam. Iure qui omnis corrupti nihil beatae. Iure voluptatibus et omnis saepe. Sit ipsam sunt. Voluptatem modi deserunt at quia iure pariatur. Qui qui velit delectus animi eum ad nobis qui.",
                            ProductId = new Guid("78052cdc-dc65-461e-b322-01758f13ddc2"),
                            Title = "Necessitatibus consequatur architecto est consequatur."
                        },
                        new
                        {
                            Id = new Guid("ace7402a-0e3b-4d64-8575-28b81076d80e"),
                            Comment = "Maxime quia corporis atque accusamus et quasi rerum. Labore qui delectus qui quo nisi cumque officia enim. Sunt quam odio explicabo corporis. Molestiae et accusantium molestiae. Ullam molestiae dolorum quia.\n\nVoluptatem non facere voluptatem voluptatem eaque. Vero dignissimos illum qui aliquid rerum ipsam harum. Qui non quam quaerat id. Est qui tempora modi molestiae est error corrupti.\n\nVeniam et in laudantium laudantium commodi eligendi et. Eligendi magni a tempora. Saepe qui repellendus aut et. Amet natus voluptatem assumenda mollitia ratione. Enim eos occaecati fugit numquam ipsam consequatur distinctio. Fugit molestiae minus in reiciendis.",
                            ProductId = new Guid("ffdbd5d2-2036-4ac7-872a-1e1642af2d35"),
                            Title = "Aperiam accusamus recusandae ea veritatis illo dolor eaque hic."
                        },
                        new
                        {
                            Id = new Guid("bd8c27aa-eab7-47fa-a793-b05d4d301705"),
                            Comment = "Non consequuntur sed qui vero. Et quibusdam iste omnis numquam in sint voluptas velit recusandae. Aut quia quisquam illum. Et id ex laboriosam neque ratione magni. Sint rerum dolorum velit aut qui qui deleniti. Reiciendis hic distinctio et eos quos voluptate.\n\nSoluta dignissimos modi ea quo quis nemo sit. Mollitia consequatur quibusdam excepturi. Illum id libero adipisci dolore qui est accusantium tempora. Repellat quis tempore voluptate cumque consequuntur earum. Nihil labore sapiente ducimus repudiandae officiis.\n\nConsequuntur atque ducimus facilis voluptatem et inventore. Ut vitae labore labore itaque debitis sint deleniti corporis illo. Harum magni architecto atque accusantium in ut eum unde voluptatem.",
                            ProductId = new Guid("a1c5cf0c-ff9b-485c-a671-c29c72d7fa5f"),
                            Title = "Occaecati quia dolorem nesciunt est nihil magnam et."
                        },
                        new
                        {
                            Id = new Guid("fa9912bc-6166-4e9b-810e-e359e78164e3"),
                            Comment = "Quisquam et maxime. Sed qui quia atque. Omnis eum laborum qui facere sequi non cum reiciendis praesentium. Dicta dolorem inventore doloremque similique sed quisquam. Ab ipsum ea non accusamus rem voluptatem consectetur et similique. Nemo est incidunt.\n\nDoloribus ipsam sed. Soluta dolores ad unde expedita. Provident ut omnis incidunt debitis. Cum sit id autem provident pariatur ea ad.\n\nQuas nam id fugiat velit et nulla. Ex sit ut saepe ipsam possimus voluptatem. Quam ipsam laboriosam eligendi saepe sunt consequuntur nemo. Eaque et a nesciunt minima earum numquam quia.",
                            ProductId = new Guid("5b007f1b-d0fd-4d8d-9fb9-8be48886bd76"),
                            Title = "Nisi voluptatibus sed."
                        },
                        new
                        {
                            Id = new Guid("25b2f990-f9fb-4ca0-9373-fe8951fd6cea"),
                            Comment = "Rerum sunt est autem molestiae libero natus impedit. Quibusdam sit quia id voluptatem laborum id iure aut. Eveniet ullam debitis recusandae quae praesentium omnis voluptas. Sit maxime odit possimus fugit autem non corrupti tempore.\n\nAut temporibus earum quo animi voluptate mollitia. Reprehenderit architecto blanditiis occaecati in enim. Nihil nihil pariatur omnis id fugiat voluptatem beatae officiis est. Possimus sit eaque et ratione. Aliquid perspiciatis nihil qui at ipsum neque.\n\nIllum consequatur exercitationem sapiente ea facilis ea quos consequatur. A a voluptas consectetur qui debitis delectus saepe illo. Explicabo fugit nesciunt dolorem autem odio magni ad impedit. Laudantium cupiditate aut quas nesciunt voluptatum. Deleniti omnis commodi officia. Ducimus error totam nihil deleniti aut.",
                            ProductId = new Guid("1f1608cf-bcce-48d5-a4d0-19df4ad0b01f"),
                            Title = "Animi deleniti repudiandae aut est voluptatem placeat quas."
                        },
                        new
                        {
                            Id = new Guid("5daaf9e8-bf86-4ae0-85eb-baaea2e6a242"),
                            Comment = "Dignissimos consequatur est vel harum vitae. Eius esse culpa reprehenderit libero provident doloribus labore. Veniam doloribus minus et fuga nostrum sunt. Autem sit et.\n\nQuo est quia rem iusto eum voluptate saepe vel ipsum. Delectus qui debitis cumque cumque amet sapiente. Quis illum magnam dolorum et quis. Eaque ut aut aut voluptatum. Non eos sunt fugit veniam ipsam enim et repudiandae omnis. Velit ut quo.\n\nEligendi velit voluptatem qui molestiae rem ratione qui tenetur quia. Quis ut atque porro. Consequatur ea qui consequatur molestiae velit ut consectetur. Laudantium reprehenderit aspernatur natus. Ut fugiat dolore et nisi voluptas temporibus quos ab corporis. Non enim accusantium quia.",
                            ProductId = new Guid("ca0a33b8-d8bb-4111-adfe-d0bfe99b6829"),
                            Title = "Rem sunt sit dolores."
                        },
                        new
                        {
                            Id = new Guid("b5733d4c-54ef-49ee-a06f-585d0400f579"),
                            Comment = "Iusto voluptates ut aliquid et est nostrum officiis. Sapiente quo neque ut dolores ipsam. Inventore et temporibus culpa voluptatem.\n\nFacere tenetur nobis asperiores quia. Consequatur sunt reiciendis illo tenetur omnis quae. Perferendis quo cum nulla libero nostrum et consequuntur et. Nam fugit facilis consequatur sit.\n\nPlaceat dolor et ut consequuntur qui quasi a tempore natus. Reiciendis qui et impedit libero id voluptate. Ratione autem molestias autem id voluptatem autem qui et numquam. Inventore est hic voluptatem dicta ipsa incidunt illo.",
                            ProductId = new Guid("bfd1ad24-fa5b-4778-a487-b7deb72f711c"),
                            Title = "Rerum in et vitae odio sit porro."
                        },
                        new
                        {
                            Id = new Guid("05faa885-818e-44b6-8a00-3dcc4ee4c3a9"),
                            Comment = "Aut et sint minima nihil. Minus natus eum quaerat ea asperiores consequuntur quis. Voluptas qui explicabo.\n\nTempore nisi aliquam nam alias. Harum molestiae error laboriosam vel neque. Laboriosam distinctio sed perspiciatis asperiores id error. Architecto dolorem vel nemo doloremque voluptates sit. Dolor maiores eligendi repellendus qui. Ipsum est quo sed in et odit sapiente.\n\nTempora exercitationem nisi tempora labore illum dignissimos atque ut perspiciatis. Atque corporis pariatur ipsa voluptatem a et ipsum ut. Sed ab quia commodi dolore doloremque aut. Facilis minima libero neque. Nihil ab quia.",
                            ProductId = new Guid("98d66ea7-e527-4991-817f-1d1f77d9a792"),
                            Title = "Autem et et est aut."
                        },
                        new
                        {
                            Id = new Guid("a9cfae22-19fe-4cad-9234-816962cf5dd0"),
                            Comment = "Autem consequatur eum reiciendis. Maiores animi suscipit nam blanditiis doloribus minus. Consectetur incidunt soluta et pariatur aut natus. Culpa placeat possimus tenetur laudantium veritatis id. Iure sunt in iure eaque. Dolor exercitationem doloremque voluptatibus.\n\nError ratione et iste in. Quod enim beatae quam. Et est sunt unde ut odio aperiam modi sit velit. Ea commodi dolorem unde voluptas. Eum magni aut veniam velit harum. Ut dolores magni voluptatem quasi qui nemo.\n\nEst corporis tenetur similique aut. Ut veritatis et similique quae suscipit recusandae. Ea sint aperiam consequatur distinctio qui id et. Delectus architecto vero quaerat eum perferendis corrupti dolores.",
                            ProductId = new Guid("f083f613-b852-4a04-8dad-9911bbfe0e82"),
                            Title = "Dicta inventore quas eos veniam."
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Backpacks.Backpack", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BackpackType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasDiscriminator().HasValue("Backpack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfd3e80e-4e67-42b3-9a1e-1c5599786205"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 5, 1, 7, 42, 15, 768, DateTimeKind.Unspecified).AddTicks(3220), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Plastic Sausages",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=227&blur",
                            Price = 978.08m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 2,
                            Stock = 7,
                            BackpackType = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("4f977bb7-72d0-464b-aafd-4827c94a0a07"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 4, 21, 0, 35, 26, 699, DateTimeKind.Unspecified).AddTicks(4147), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Soft Fish",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=351&blur",
                            Price = 181.18m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 6,
                            Stock = 2794,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("9bc16d1d-6a51-4281-9c35-99432d0eca9a"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 27, 20, 30, 27, 276, DateTimeKind.Unspecified).AddTicks(2598), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Steel Shirt",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=912&blur",
                            Price = 114.61m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 1,
                            Stock = 2823,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("ad1d0233-e24b-47eb-a65a-c6600f350221"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 3, 4, 26, 29, 489, DateTimeKind.Unspecified).AddTicks(3672), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Fresh Salad",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=925&blur",
                            Price = 421.78m,
                            ProductTypeId = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412"),
                            Rating = 9,
                            Stock = 2679,
                            BackpackType = "Snowsports"
                        },
                        new
                        {
                            Id = new Guid("4759a39a-510d-4f9d-836b-81487935d9b2"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 5, 10, 1, 36, 343, DateTimeKind.Unspecified).AddTicks(3867), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Intelligent Granite Fish",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=244&blur",
                            Price = 588.12m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 4,
                            Stock = 1964,
                            BackpackType = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("9682b5e3-6a08-4323-945a-2afc6f868069"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 8, 13, 14, 40, 82, DateTimeKind.Unspecified).AddTicks(2617), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Small Wooden Salad",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=659&blur",
                            Price = 685.77m,
                            ProductTypeId = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412"),
                            Rating = 1,
                            Stock = 1852,
                            BackpackType = "Hiking"
                        },
                        new
                        {
                            Id = new Guid("327957fa-7dfd-415f-97e1-2b46719a86a0"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 30, 1, 4, 53, 375, DateTimeKind.Unspecified).AddTicks(8461), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Generic Concrete Shirt",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1015&blur",
                            Price = 977.68m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 8,
                            Stock = 38,
                            BackpackType = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("816852bd-2913-491d-b205-93a2f26975c5"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 25, 6, 5, 29, 830, DateTimeKind.Unspecified).AddTicks(8756), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Granite Sausages",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=373&blur",
                            Price = 775.58m,
                            ProductTypeId = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412"),
                            Rating = 2,
                            Stock = 1232,
                            BackpackType = "Overnight"
                        },
                        new
                        {
                            Id = new Guid("a4c571f4-d6fe-44ed-8917-420fea29e8aa"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 9, 6, 17, 55, 26, 987, DateTimeKind.Unspecified).AddTicks(2389), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Handcrafted Rubber Table",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=18&blur",
                            Price = 540.30m,
                            ProductTypeId = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412"),
                            Rating = 2,
                            Stock = 1809,
                            BackpackType = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("8b8c464a-05e5-4b4d-8012-91405b8531d8"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 10, 14, 47, 48, 751, DateTimeKind.Unspecified).AddTicks(6164), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Frozen Salad",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=52&blur",
                            Price = 780.15m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 4,
                            Stock = 7,
                            BackpackType = "Overnight"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Boots.Boot", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<string>("BootType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Boot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70d70ad7-9b33-4c55-8e45-4cca87137ac3"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 19, 2, 40, 1, 890, DateTimeKind.Unspecified).AddTicks(1737), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Steel Keyboard",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=26&blur",
                            Price = 823.38m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 6,
                            Stock = 1442,
                            BootType = "Cowboy",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("2cae3c54-4daf-4106-8c32-a7237fa880a7"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 16, 19, 1, 7, 130, DateTimeKind.Unspecified).AddTicks(4129), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Tasty Plastic Shirt",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=614&blur",
                            Price = 877.68m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 4,
                            Stock = 4537,
                            BootType = "Football",
                            Size = 24
                        },
                        new
                        {
                            Id = new Guid("e106e0a6-35dd-4b5c-b43e-6e3290d0b2ff"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 1, 8, 0, 3, 22, 374, DateTimeKind.Unspecified).AddTicks(1778), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Licensed Frozen Fish",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=222&blur",
                            Price = 453.13m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 7,
                            Stock = 509,
                            BootType = "Cowboy",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("4fe76041-da71-45a9-83d2-5bbc91b8979f"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 10, 12, 0, 4, 11, DateTimeKind.Unspecified).AddTicks(8389), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Granite Shoes",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=537&blur",
                            Price = 255.42m,
                            ProductTypeId = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412"),
                            Rating = 9,
                            Stock = 1494,
                            BootType = "Harness",
                            Size = 22
                        },
                        new
                        {
                            Id = new Guid("5c71a42a-90fa-495d-af1f-dfcf61065e15"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 24, 1, 53, 28, 702, DateTimeKind.Unspecified).AddTicks(7512), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Granite Computer",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=770&blur",
                            Price = 576.72m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 5,
                            Stock = 217,
                            BootType = "Football",
                            Size = 20
                        },
                        new
                        {
                            Id = new Guid("49b5c9ba-da6f-4948-9e76-f0ad41e59cad"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 4, 17, 16, 54, 19, 14, DateTimeKind.Unspecified).AddTicks(5102), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Concrete Salad",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=433&blur",
                            Price = 78.69m,
                            ProductTypeId = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412"),
                            Rating = 8,
                            Stock = 1519,
                            BootType = "Engineer",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("0cca14e7-767a-4906-8dc7-1e53b14442ca"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 3, 19, 22, 11, 754, DateTimeKind.Unspecified).AddTicks(3283), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Practical Concrete Car",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1075&blur",
                            Price = 923.98m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 10,
                            Stock = 3209,
                            BootType = "Cowboy",
                            Size = 21
                        },
                        new
                        {
                            Id = new Guid("4a6e0b20-4733-4de9-8072-3002dc0e3b40"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 2, 6, 23, 7, 48, 218, DateTimeKind.Unspecified).AddTicks(6105), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Refined Rubber Sausages",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=704&blur",
                            Price = 665.97m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 3,
                            Stock = 4838,
                            BootType = "Engineer",
                            Size = 22
                        },
                        new
                        {
                            Id = new Guid("3ff051dc-990e-4c93-b9a9-7b4a0fdd366b"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 15, 2, 33, 16, 570, DateTimeKind.Unspecified).AddTicks(7401), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Incredible Granite Fish",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=68&blur",
                            Price = 191.02m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 9,
                            Stock = 2985,
                            BootType = "Harness",
                            Size = 26
                        },
                        new
                        {
                            Id = new Guid("5991d3c5-4614-4c3b-80aa-ddf6f07a462a"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 26, 16, 43, 40, 666, DateTimeKind.Unspecified).AddTicks(5178), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Plastic Bacon",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=426&blur",
                            Price = 253.08m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 10,
                            Stock = 2553,
                            BootType = "Harness",
                            Size = 26
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Kayaks.Kayak", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product");

                    b.Property<int>("AmountOfPerson")
                        .HasColumnType("int");

                    b.Property<string>("KayakType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasDiscriminator().HasValue("Kayak");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e852fab1-4dc0-46ec-a9db-184e4b8d96a6"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 10, 28, 5, 21, 25, 818, DateTimeKind.Unspecified).AddTicks(9159), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Fantastic Metal Chicken",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=348&blur",
                            Price = 762.10m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 3,
                            Stock = 2636,
                            AmountOfPerson = 2,
                            KayakType = "Racing"
                        },
                        new
                        {
                            Id = new Guid("78052cdc-dc65-461e-b322-01758f13ddc2"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 6, 9, 18, 23, 54, 307, DateTimeKind.Unspecified).AddTicks(1637), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Rubber Chair",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=2&blur",
                            Price = 300.35m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 10,
                            Stock = 2793,
                            AmountOfPerson = 3,
                            KayakType = "Camping"
                        },
                        new
                        {
                            Id = new Guid("ffdbd5d2-2036-4ac7-872a-1e1642af2d35"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 1, 17, 35, 4, 88, DateTimeKind.Unspecified).AddTicks(5976), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Rubber Keyboard",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=866&blur",
                            Price = 280.30m,
                            ProductTypeId = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412"),
                            Rating = 2,
                            Stock = 221,
                            AmountOfPerson = 2,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("a1c5cf0c-ff9b-485c-a671-c29c72d7fa5f"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 31, 15, 29, 20, 438, DateTimeKind.Unspecified).AddTicks(6762), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Frozen Tuna",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=22&blur",
                            Price = 161.00m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 0,
                            Stock = 1583,
                            AmountOfPerson = 3,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("5b007f1b-d0fd-4d8d-9fb9-8be48886bd76"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 7, 31, 17, 23, 47, 807, DateTimeKind.Unspecified).AddTicks(7624), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Fresh Pants",
                            Option = "Three",
                            PhotoUrl = "https://picsum.photos/500/375/?image=866&blur",
                            Price = 188.39m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 5,
                            Stock = 1478,
                            AmountOfPerson = 1,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("1f1608cf-bcce-48d5-a4d0-19df4ad0b01f"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 12, 1, 8, 46, 29, 426, DateTimeKind.Unspecified).AddTicks(1798), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Wooden Bike",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=805&blur",
                            Price = 733.02m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 10,
                            Stock = 2186,
                            AmountOfPerson = 3,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("ca0a33b8-d8bb-4111-adfe-d0bfe99b6829"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 5, 27, 0, 30, 16, 838, DateTimeKind.Unspecified).AddTicks(1280), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Sleek Fresh Chair",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=706&blur",
                            Price = 936.44m,
                            ProductTypeId = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412"),
                            Rating = 1,
                            Stock = 166,
                            AmountOfPerson = 2,
                            KayakType = "Family"
                        },
                        new
                        {
                            Id = new Guid("bfd1ad24-fa5b-4778-a487-b7deb72f711c"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IntroduceAt = new DateTimeOffset(new DateTime(2022, 3, 1, 3, 54, 17, 937, DateTimeKind.Unspecified).AddTicks(645), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Cotton Ball",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=1075&blur",
                            Price = 50.12m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 0,
                            Stock = 3560,
                            AmountOfPerson = 3,
                            KayakType = "Diving"
                        },
                        new
                        {
                            Id = new Guid("98d66ea7-e527-4991-817f-1d1f77d9a792"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 11, 22, 10, 26, 13, 976, DateTimeKind.Unspecified).AddTicks(8238), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Gorgeous Steel Bike",
                            Option = "One",
                            PhotoUrl = "https://picsum.photos/500/375/?image=446&blur",
                            Price = 861.32m,
                            ProductTypeId = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80"),
                            Rating = 8,
                            Stock = 1010,
                            AmountOfPerson = 3,
                            KayakType = "Fishing"
                        },
                        new
                        {
                            Id = new Guid("f083f613-b852-4a04-8dad-9911bbfe0e82"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IntroduceAt = new DateTimeOffset(new DateTime(2021, 8, 7, 3, 35, 16, 525, DateTimeKind.Unspecified).AddTicks(1487), new TimeSpan(0, -3, 0, 0, 0)),
                            Name = "Rustic Rubber Table",
                            Option = "Two",
                            PhotoUrl = "https://picsum.photos/500/375/?image=63&blur",
                            Price = 79.46m,
                            ProductTypeId = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1"),
                            Rating = 2,
                            Stock = 1537,
                            AmountOfPerson = 1,
                            KayakType = "Racing"
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeOne", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeOne");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f0631e5-a1f0-4abc-845a-c23614c03412")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeThree", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeThree");

                    b.HasData(
                        new
                        {
                            Id = new Guid("daeca18f-9b56-4990-88a4-5537c48a5e80")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.TypeTwo", b =>
                {
                    b.HasBaseType("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType");

                    b.HasDiscriminator().HasValue("TypeTwo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a88b5a9-79e5-47bd-b8ae-5bdbafa19df1")
                        });
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.ValueObjects.ProductTypes.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dotnet6.GraphQL4.Store.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
